
export const facts: string[] = [
    "LightSide is very trustworthy!",
    "One Solar Whale is as big as Central Park in NYC.",
    "99% of gamblers quit before winning big. Keep buying boxes!",
    "Base X20 Large Miners are worse than fully upgraded X10 Medium Miners",
    "Servers typically last between 8-9 weeks.",
    "The chat censor is very annoying.",
    "Using multiple X20 Large Miners will not result in faster building.",
    "Trojite cannot be stolen from cities they are deposited to.",
    "The Radiation Zone in Data Recovery servers gradually expands after every cycle.",
    "Pathing is very good and not flawed in any ways.",
    "Reinforce a fleet and retreat those reinforcements before they reach their target to maximize battlepass points from AP spent.",
    "The free side of the battlepass provides 3,000 proxima coins, 431,000 UECoins, and 19 Black Market boxes.",
    "The paid side of the battlepass provides 6,000 proxima coins, 320,000 UECoins, and 20 Black Market boxes.",
    "The paid battlepass gives the best value for your buck in the game.",
    "Cities provide slightly more occupancy percentage than they say they do.",
    "Miners assigned to an Advanced Mining Platform will update their Tech Point allocations after depositing at the AMP.",
    "Fleets will only update their Tech Point allocations when inside the base or outpost/platform if deployed as a subfleet.",
    "Outposts and Basic Mining Platforms take the least amount of time to build.",
    "There is still extra time left in the server after the rating point timer.",
    "Graveyards are square-ish in shape, do not have any level 3 or higher resource nodes, and can be found in any of the starter regions.",
    "If you are a leader, 90% of this game is actually played on Discord.",
    "Trying to sign an agreement in the hub is fun for the whole family!",
    "Fleets can travel through the center of the sun, but cannot land inside the center of the sun.",
    "Ships, including miners, can be permanently killed by using ships or aircraft with the \"Attack Against Systems: Propulsion System\" attribute.",
    "Rallies are a bad idea.",
    "The shop refreshes everyday at 00:00 UTC.",
    "Some liveries are pretty cool.",
    "Some liveries are atrocious, and if you buy them, you are a sociopath. Seek help.",
    "Stop spelling \"Quaoar\" incorrectly. It has feelings too.",
    "Relocating via an outpost will not stop or reset your peace shield timer.",
    "Aircraft in the Aircraft Defense Fleet are invincible and cannot be killed by any means while defending the base.",
    "Tech Point Restoration Items can only be bought twice per server. Use them wisely.",
    "Solar Whales can hold up to 16 aircraft at a time!",
    "In trojite servers, destroying a base will give you half of the base's stored trojite.",
    "In trojite servers, having your base destroyed will reset your base's stored trojite to 0.",
    "You can let your fleets escape a blockade around your base by deploying them as a subfleet to an outpost/platform somewhere else.",
    "If you are located in a Scattered Asteroid Belt, you cannot send super capital ships out, but they will still defend your base.",
    "Docking points inside a city will only give their benefits if the city is owned by your community.",
    "Learn how to convert UTC to your timezone - it'll help with coordinating with others.",
    "You can have multiple player identities linked to the same account!",
    "All module data in Module Library is crowdsourced! If you'd like to contribute, reach out to me. Your help is greatly appreciated!"
];
