
type Ship = {
    name: string;
    title: string;
    img: string;
    type: "Fighter" | "Corvette" | "Frigate" | "Destroyer" | "Cruiser" | "Battlecruiser" | "Auxiliary Ship" | "Carrier";
    variant: "A" | "B" | "C" | "D";
    variant_name: string;
    manufacturer: "Jupiter Industry" | "NOMA Shipping" | "Antonios" | "Dawn Accord" | "Empty";
    direction: ("Outstanding Firepower" | "Sustained Combat" | "Strategy & Support" | "Fighter & Corvette" | "Empty")[];
    scope: "Direct-Fire Weapon" | "Projectile Weapon" | "Empty";
    weight: number;
}

const data: Ship[] = [{
        name: "AT021",
        title: "Pulse Attacker",
        img: "/ships/at021_a.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Dawn Accord",
        direction: ["Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "AT021",
        title: "Tactical Attacker",
        img: "/ships/at021_b.png",
        type: "Fighter",
        variant: "B",
        variant_name: "Interference Type",
        manufacturer: "Dawn Accord",
        direction: ["Sustained Combat", "Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "AT021",
        title: "Heavy Attacker",
        img: "/ships/at021_c.png",
        type: "Fighter",
        variant: "C",
        variant_name: "Multi-Role Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "B192 Newland",
        title: "Heavy Attacker",
        img: "/ships/b192newland.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Multi-Role Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "BR050",
        title: "Standard Bomber",
        img: "/ships/br050_a.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "BR050",
        title: "Multi-Role Bomber",
        img: "/ships/br050_b.png",
        type: "Fighter",
        variant: "B",
        variant_name: "Defense Type",
        manufacturer: "Dawn Accord",
        direction: ["Sustained Combat", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "BR050",
        title: "Torpedo Bomber",
        img: "/ships/br050_c.png",
        type: "Fighter",
        variant: "C",
        variant_name: "Torpedo Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Balancer Anderson SC020",
        title: "Scout",
        img: "/ships/sc020.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Interference Type",
        manufacturer: "Antonios",
        direction: ["Sustained Combat", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Bullfrog",
        title: "Dual-Purpose Bomber",
        img: "/ships/bullfrog.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Siege Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Hayreddin's Loyal",
        title: "Pulsar Fighter",
        img: "/ships/hayreddinsLoyal.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Special Type",
        manufacturer: "Empty",
        direction: ["Outstanding Firepower", "Sustained Combat", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Janbiya Aer410",
        title: "Assault Attacker",
        img: "/ships/janbiyaAer410.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Mistral",
        title: "Combat Attacker",
        img: "/ships/mistral.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Antonios",
        direction: ["Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "SC002",
        title: "Quantum Scout",
        img: "/ships/sc002.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Generic Type",
        manufacturer: "Dawn Accord",
        direction: ["Sustained Combat", "Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Sandrake",
        title: "Atmospheric Interceptor",
        img: "/ships/sandrake.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Dual-Purpose Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Spore A404",
        title: "Light Fighter",
        img: "/ships/sporeA404.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Stingray",
        title: "Torpedo Bomber",
        img: "/ships/stingray.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Stealth Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Strix A100",
        title: "Joint Attacker",
        img: "/ships/strixA100.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "NOMA Shipping",
        direction: ["Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Vitas A021",
        title: "Heavy Attacker",
        img: "/ships/vitasA021.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Vitas-B010",
        title: "Bomber",
        img: "/ships/vitasB010.png",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Sustained Combat", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "CV-II003",
        title: "Light Corvette",
        img: "/ships/cvii003.png",
        type: "Corvette",
        variant: "A",
        variant_name: "Multi-Role Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "CV-M011",
        title: "Heavy Missile Corvette",
        img: "/ships/cvm011_a.png",
        type: "Corvette",
        variant: "A",
        variant_name: "Missile Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Sustained Combat", "Strategy & Support", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "CV-M011",
        title: "Heavy Cannon Corvette",
        img: "/ships/cvm011_b.png",
        type: "Corvette",
        variant: "B",
        variant_name: "Cannon Type",
        manufacturer: "Dawn Accord",
        direction: ["Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "CV-M011",
        title: "High-Speed Missile Corvette",
        img: "/ships/cvm011_c.png",
        type: "Corvette",
        variant: "C",
        variant_name: "High-Speed Type",
        manufacturer: "Dawn Accord",
        direction: ["Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "CV-T800",
        title: "Pulsar Corvette",
        img: "/ships/cvt800.png",
        type: "Corvette",
        variant: "A",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Cellular Defender",
        title: "Heavy Torpedo Corvette",
        img: "/ships/cellularDefender.png",
        type: "Corvette",
        variant: "A",
        variant_name: "Multi-Role Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Nebula Chaser",
        title: "Heavy Corvette",
        img: "/ships/nebulaChaser_a.png",
        type: "Corvette",
        variant: "A",
        variant_name: "Ballistic Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Nebula Chaser",
        title: "Pulsar Corvette",
        img: "/ships/nebulaChaser_b.png",
        type: "Corvette",
        variant: "B",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "RedBeast 7-13",
        title: "Missile Corvette",
        img: "/ships/redbeast713.png",
        type: "Corvette",
        variant: "A",
        variant_name: "Offensive Type",
        manufacturer: "NOMA Shipping",
        direction: ["Sustained Combat", "Strategy & Support", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "S-Levy 9",
        title: "Heavy Torpedo Escort Corvette",
        img: "/ships/slevy9.png",
        type: "Corvette",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Silent Assassin",
        title: "Armored Corvette",
        img: "/ships/silentAssassin.png",
        type: "Corvette",
        variant: "A",
        variant_name: "High-Speed Type",
        manufacturer: "NOMA Shipping",
        direction: ["Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Void Elfin",
        title: "Stealth Missile Corvette",
        img: "/ships/voidElfin.png",
        type: "Corvette",
        variant: "A",
        variant_name: "Offensive Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Sustained Combat", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Carilion",
        title: "Recon Frigate",
        img: "/ships/carilion_a.png",
        type: "Frigate",
        variant: "A",
        variant_name: "Recon Type",
        manufacturer: "Antonios",
        direction: ["Sustained Combat", "Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Carilion",
        title: "Heavy Cannon Frigate",
        img: "/ships/carilion_b.png",
        type: "Frigate",
        variant: "B",
        variant_name: "Heavy Cannon Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Carilion",
        title: "Special Frigate",
        img: "/ships/carilion_c.png",
        type: "Frigate",
        variant: "C",
        variant_name: "Special Type",
        manufacturer: "Antonios",
        direction: ["Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "FG300",
        title: "Multi-Role Frigate",
        img: "/ships/fg300_a.png",
        type: "Frigate",
        variant: "A",
        variant_name: "Multi-Role Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "FG300",
        title: "Armored Frigate",
        img: "/ships/fg300_b.png",
        type: "Frigate",
        variant: "B",
        variant_name: "Armored Type",
        manufacturer: "Dawn Accord",
        direction: ["Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "FG300",
        title: "Recon Frigate",
        img: "/ships/fg300_c.png",
        type: "Frigate",
        variant: "C",
        variant_name: "Recon Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Mare Imbrium",
        title: "Assault Frigate",
        img: "/ships/mareImbrium_a.png",
        type: "Frigate",
        variant: "A",
        variant_name: "Railgun Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Mare Imbrium",
        title: "Experimental Pulse Cannon Frigate",
        img: "/ships/mareImbrium_b.png",
        type: "Frigate",
        variant: "B",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Mare Nubium",
        title: "Light Landing Ship",
        img: "/ships/mareNubium_a.png",
        type: "Frigate",
        variant: "A",
        variant_name: "Assault Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Mare Nubium",
        title: "Anti-Aircraft Frigate",
        img: "/ships/mareNubium_b.png",
        type: "Frigate",
        variant: "B",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Jupiter Industry",
        direction: ["Empty"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Mare Serenitatis",
        title: "Heavy Frigate",
        img: "/ships/mareSerenitatis_a.png",
        type: "Frigate",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Mare Serenitatis",
        title: "Missile Frigate",
        img: "/ships/mareSerenitatis_b.png",
        type: "Frigate",
        variant: "B",
        variant_name: "Missile Type",
        manufacturer: "Jupiter Industry",
        direction: ["Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Mare Serenitatis",
        title: "Anti-Aircraft Frigate",
        img: "/ships/mareSerenitatis_c.png",
        type: "Frigate",
        variant: "C",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Jupiter Industry",
        direction: ["Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Mare Tranquillitatis",
        title: "Missile Frigate",
        img: "/ships/mareTranquillitatis_a.png",
        type: "Frigate",
        variant: "A",
        variant_name: "Integrated Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Mare Tranquillitatis",
        title: "Pulse Cannon Frigate",
        img: "/ships/mareTranquillitatis_b.png",
        type: "Frigate",
        variant: "B",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Jupiter Industry",
        direction: ["Empty"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Mare Tranquillitatis",
        title: "Interceptor Frigate",
        img: "/ships/mareTranquillitatis_c.png",
        type: "Frigate",
        variant: "C",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "NOMA M470",
        title: "Heavy Landing Ship",
        img: "/ships/nomaM470_a.png",
        type: "Frigate",
        variant: "A",
        variant_name: "Siege Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower"],
        scope: "Empty",
        weight: 10
    }, {
        name: "NOMA M470",
        title: "Support Frigate",
        img: "/ships/nomaM470_b.png",
        type: "Frigate",
        variant: "B",
        variant_name: "Support Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "NOMA M470",
        title: "Anti-Aircraft Frigate",
        img: "/ships/nomaM470_c.png",
        type: "Frigate",
        variant: "C",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Reliat",
        title: "Rapid Torpedo Frigate",
        img: "/ships/reliat_a.png",
        type: "Frigate",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Reliat",
        title: "Tactical Torpedo Frigate",
        img: "/ships/reliat_b.png",
        type: "Frigate",
        variant: "B",
        variant_name: "Torpedo Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Reliat",
        title: "Stealth Frigate",
        img: "/ships/reliat_c.png",
        type: "Frigate",
        variant: "C",
        variant_name: "Stealth Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Ruby",
        title: "Heavy Railgun Frigate",
        img: "/ships/ruby_a.png",
        type: "Frigate",
        variant: "A",
        variant_name: "Railgun Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Ruby",
        title: "Experimental Ion Cannon Frigate",
        img: "/ships/ruby_b.png",
        type: "Frigate",
        variant: "B",
        variant_name: "Ion Cannon Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Ruby",
        title: "Defensive Frigate",
        img: "/ships/ruby_c.png",
        type: "Frigate",
        variant: "C",
        variant_name: "Defensive Type",
        manufacturer: "NOMA Shipping",
        direction: ["Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "XenoStinger",
        title: "Tactical Frigate",
        img: "/ships/xenostinger_a.png",
        type: "Frigate",
        variant: "A",
        variant_name: "Special Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower"],
        scope: "Empty",
        weight: 5
    }, {
        name: "XenoStinger",
        title: "Defensive Frigate",
        img: "/ships/xenostinger_b.png",
        type: "Frigate",
        variant: "B",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 5
    }, {
        name: "AC721",
        title: "Heavy Logistics Destroyer",
        img: "/ships/ac721_a.png",
        type: "Destroyer",
        variant: "A",
        variant_name: "Generic Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "AC721",
        title: "Heavy Missile Destroyer",
        img: "/ships/ac721_b.png",
        type: "Destroyer",
        variant: "B",
        variant_name: "Missile Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "AC721",
        title: "Heavy Dual-Purpose Assault Ship",
        img: "/ships/ac721_d.png",
        type: "Destroyer",
        variant: "D",
        variant_name: "Aircraft Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Aldabra",
        title: "Heavy Cannon Destroyer",
        img: "/ships/aldabra_a.png",
        type: "Destroyer",
        variant: "A",
        variant_name: "Generic Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Aldabra",
        title: "Heavy Assault Destroyer",
        img: "/ships/aldabra_b.png",
        type: "Destroyer",
        variant: "B",
        variant_name: "Armored Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Ceres",
        title: "Aircraft Destroyer",
        img: "/ships/ceres_a.png",
        type: "Destroyer",
        variant: "A",
        variant_name: "Aircraft Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Ceres",
        title: "Support Destroyer",
        img: "/ships/ceres_b.png",
        type: "Destroyer",
        variant: "B",
        variant_name: "Support Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Ceres",
        title: "Tactical Destroyer",
        img: "/ships/ceres_c.png",
        type: "Destroyer",
        variant: "C",
        variant_name: "Tactical Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Eris I",
        title: "Maneuver Assault Destroyer",
        img: "/ships/eris_a.png",
        type: "Destroyer",
        variant: "A",
        variant_name: "Cannon Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Eris I",
        title: "Heavy Cannon Destroyer",
        img: "/ships/eris_b.png",
        type: "Destroyer",
        variant: "B",
        variant_name: "Heavy Cannon Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Eris I",
        title: "Armored Destroyer",
        img: "/ships/eris_c.png",
        type: "Destroyer",
        variant: "C",
        variant_name: "Armored Type",
        manufacturer: "Jupiter Industry",
        direction: ["Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Guardian",
        title: "Support Destroyer",
        img: "/ships/guardian_a.png",
        type: "Destroyer",
        variant: "A",
        variant_name: "Support Type",
        manufacturer: "Antonios",
        direction: ["Empty"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Guardian",
        title: "Dual-Purpose Assault Ship",
        img: "/ships/guardian_b.png",
        type: "Destroyer",
        variant: "B",
        variant_name: "Dual-Purpose Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Guardian",
        title: "Experimental Pulse Assault Ship",
        img: "/ships/guardian_c.png",
        type: "Destroyer",
        variant: "C",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Quaoar",
        title: "Railgun Destroyer",
        img: "/ships/quaoar_a.png",
        type: "Destroyer",
        variant: "A",
        variant_name: "Railgun Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Quaoar",
        title: "Torpedo Destroyer",
        img: "/ships/quaoar_b.png",
        type: "Destroyer",
        variant: "B",
        variant_name: "Torpedo Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Taurus",
        title: "Pulse Cannon Destroyer",
        img: "/ships/taurus_a.png",
        type: "Destroyer",
        variant: "A",
        variant_name: "Offensive Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Taurus",
        title: "Assault Destroyer",
        img: "/ships/taurus_b.png",
        type: "Destroyer",
        variant: "B",
        variant_name: "Assault Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Taurus",
        title: "Defensive Destroyer",
        img: "/ships/taurus_c.png",
        type: "Destroyer",
        variant: "C",
        variant_name: "Defensive Type",
        manufacturer: "NOMA Shipping",
        direction: ["Sustained Combat", "Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Tundra",
        title: "Tactical Destroyer",
        img: "/ships/tundra_a.png",
        type: "Destroyer",
        variant: "A",
        variant_name: "Support Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Tundra",
        title: "Aircraft Destroyer",
        img: "/ships/tundra_b.png",
        type: "Destroyer",
        variant: "B",
        variant_name: "Aircraft Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Winged Hussar",
        title: "Light Missile Destroyer",
        img: "/ships/wingedHussar_a.png",
        type: "Destroyer",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Winged Hussar",
        title: "Integrated Missile Destroyer",
        img: "/ships/wingedHussar_b.png",
        type: "Destroyer",
        variant: "B",
        variant_name: "Integrated Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Winged Hussar",
        title: "Area-Denial Anti-Aircraft Destroyer",
        img: "/ships/wingedHussar_c.png",
        type: "Destroyer",
        variant: "C",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Antonios",
        direction: ["Sustained Combat", "Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "CAS066",
        title: "Generic Cruiser",
        img: "/ships/cas066_a.png",
        type: "Cruiser",
        variant: "A",
        variant_name: "Integrated Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "CAS066",
        title: "Artillery Cruiser",
        img: "/ships/cas066_b.png",
        type: "Cruiser",
        variant: "B",
        variant_name: "Artillery Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "CAS066",
        title: "Aircraft Cruiser",
        img: "/ships/cas066_c.png",
        type: "Cruiser",
        variant: "C",
        variant_name: "Aircraft Type",
        manufacturer: "Dawn Accord",
        direction: ["Empty"],
        scope: "Empty",
        weight: 10
    }, {
        name: "CAS066",
        title: "Auxiliary Cruiser",
        img: "/ships/cas066_d.png",
        type: "Cruiser",
        variant: "D",
        variant_name: "Support Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Callisto",
        title: "Cluster Torpedo Raid Ship",
        img: "/ships/callisto_a.png",
        type: "Cruiser",
        variant: "A",
        variant_name: "Torpedo Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 2
    }, {
        name: "Callisto",
        title: "Heavy Torpedo Raid Ship",
        img: "/ships/callisto_b.png",
        type: "Cruiser",
        variant: "B",
        variant_name: "Anti-Ship Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 2
    }, {
        name: "Callisto",
        title: "Heavy UAV Cruiser",
        img: "/ships/callisto_c.png",
        type: "Cruiser",
        variant: "C",
        variant_name: "Support Type",
        manufacturer: "Jupiter Industry",
        direction: ["Empty"],
        scope: "Projectile Weapon",
        weight: 2
    }, {
        name: "Chimera",
        title: "Heavy Cruiser",
        img: "/ships/chimera_a.png",
        type: "Cruiser",
        variant: "A",
        variant_name: "Ballistic Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Chimera",
        title: "Cannon Cruiser",
        img: "/ships/chimera_b.png",
        type: "Cruiser",
        variant: "B",
        variant_name: "Heavy Cannon Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Chimera",
        title: "Defensive Cruiser",
        img: "/ships/chimera_c.png",
        type: "Cruiser",
        variant: "C",
        variant_name: "Defensive Type",
        manufacturer: "NOMA Shipping",
        direction: ["Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Conamara Chaos",
        title: "Railgun Cruiser",
        img: "/ships/conamaraChaos_a.png",
        type: "Cruiser",
        variant: "A",
        variant_name: "Railgun Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Conamara Chaos",
        title: "High-Speed Plasma Cruiser",
        img: "/ships/conamaraChaos_b.png",
        type: "Cruiser",
        variant: "B",
        variant_name: "Plasma Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Io",
        title: "Assault Ion Cannon Cruiser",
        img: "/ships/io_a.png",
        type: "Cruiser",
        variant: "A",
        variant_name: "Ion Cannon Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Io",
        title: "High-Speed Ion Cannon Cruiser",
        img: "/ships/io_b.png",
        type: "Cruiser",
        variant: "B",
        variant_name: "Anti-Ship Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Io",
        title: "Siege Ion Cannon Cruiser",
        img: "/ships/io_c.png",
        type: "Cruiser",
        variant: "C",
        variant_name: "Siege Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Jaeger",
        title: "Heavy Aircraft Cruiser",
        img: "/ships/jaeger_a.png",
        type: "Cruiser",
        variant: "A",
        variant_name: "Support Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 5
    }, {
        name: "Jaeger",
        title: "Heavy Cannon Cruiser",
        img: "/ships/jaeger_b.png",
        type: "Cruiser",
        variant: "B",
        variant_name: "Anti-Ship Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "KCCPV2.0",
        title: "Light Attack Cruiser",
        img: "/ships/kccpv_a.png",
        type: "Cruiser",
        variant: "A",
        variant_name: "Integrated Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "KCCPV2.0",
        title: "Light Pulse Attack Cruiser",
        img: "/ships/kccpv_b.png",
        type: "Cruiser",
        variant: "B",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "KCCPV2.0",
        title: "Light Railgun Cruiser",
        img: "/ships/kccpv_c.png",
        type: "Cruiser",
        variant: "C",
        variant_name: "Railgun Type",
        manufacturer: "Dawn Accord",
        direction: ["Empty"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "KCCPV2.0",
        title: "Light Aircraft Cruiser",
        img: "/ships/kccpv_d.png",
        type: "Cruiser",
        variant: "D",
        variant_name: "Aircraft Type",
        manufacturer: "Dawn Accord",
        direction: ["Empty"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Light Cone",
        title: "Multi-Role Missile Cruiser Cruiser",
        img: "/ships/lightCone_a.png",
        type: "Cruiser",
        variant: "A",
        variant_name: "Generic Type",
        manufacturer: "NOMA Shipping",
        direction: ["Empty"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Light Cone",
        title: "Area-Denial Anti-Aircraft Cruiser",
        img: "/ships/lightCone_b.png",
        type: "Cruiser",
        variant: "B",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Light Cone",
        title: "Offensive Missile Cruiser",
        img: "/ships/lightCone_c.png",
        type: "Cruiser",
        variant: "C",
        variant_name: "Assault Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Ranger",
        title: "Comprehensive Warfare Cruiser",
        img: "/ships/ranger_a.png",
        type: "Cruiser",
        variant: "A",
        variant_name: "Integrated Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Ranger",
        title: "Heavy Ion Cannon Cruiser",
        img: "/ships/ranger_b.png",
        type: "Cruiser",
        variant: "B",
        variant_name: "Ion Cannon Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 2
    }, {
        name: "Predator",
        title: "Aircraft Cruiser",
        img: "/ships/predator_a.png",
        type: "Cruiser",
        variant: "A",
        variant_name: "Generic Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Predator",
        title: "Tactical Aircraft Cruiser",
        img: "/ships/predator_b.png",
        type: "Cruiser",
        variant: "B",
        variant_name: "Tactical Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Predator",
        title: "Anti-Aircraft Cruiser",
        img: "/ships/predator_c.png",
        type: "Cruiser",
        variant: "C",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Constantine the Great",
        title: "Multi-Role Battlecruiser",
        img: "/ships/constantineTheGreat.png",
        type: "Battlecruiser",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 2
    }, {
        name: "Eternal Storm",
        title: "Attack Battlecruiser",
        img: "/ships/eternalStorm.png",
        type: "Battlecruiser",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 2
    }, {
        name: "Spear of Uranus",
        title: "Heavy Battlecruiser",
        img: "/ships/spearOfUranus.png",
        type: "Battlecruiser",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 2
    }, {
        name: "ST59",
        title: "Defensive Battlecruiser",
        img: "/ships/st59.png",
        type: "Battlecruiser",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Dawn Accord",
        direction: ["Sustained Combat", "Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Thunderbolt Star",
        title: "Multi-Role Arsenal Ship",
        img: "/ships/thunderboltStar.png",
        type: "Battlecruiser",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Empty",
        direction: ["Outstanding Firepower", "Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 2
    }, {
        name: "Ediacaran",
        title: "Heavy Firepower Auxiliary Ship",
        img: "/ships/ediacaran.png",
        type: "Auxiliary Ship",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Strategy & Support"],
        scope: "Empty",
        weight: 2
    }, {
        name: "FSV830",
        title: "Fast Tactical Auxiliary Ship",
        img: "/ships/fsv830.png",
        type: "Auxiliary Ship",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Dawn Accord",
        direction: ["Sustained Combat", "Strategy & Support"],
        scope: "Empty",
        weight: 5
    }, {
        name: "CV3000",
        title: "High-Speed Carrier",
        img: "/ships/cv3000.png",
        type: "Carrier",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 2
    }, {
        name: "Eternal Heavens",
        title: "UAV Carrier",
        img: "/ships/eternalHeavens.png",
        type: "Carrier",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Empty",
        weight: 2
    }, {
        name: "Marshal Crux",
        title: "Carrier",
        img: "/ships/marshalCrux.png",
        type: "Carrier",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 2
    }, {
        name: "Solar Whale",
        title: "Armed Tactical Carrier",
        img: "/ships/solarWhale.png",
        type: "Carrier",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 2
    }
];

const difficulty = {
    "Jupiter Industry": 3.5,
    "NOMA Shipping": 3.5,
    "Antonios": 4,
    "Dawn Accord": 2.5,
    "Outstanding Firepower": 5.5,
    "Sustained Combat": 5,
    "Strategy & Support": 5.5,
    "Fighter & Corvette": 6,
    "Projectile Weapon": 4.5,
    "Direct-Fire Weapon": 4
};

export { data, difficulty };
