
const difficulty = {
    "Jupiter Industry": 3.5,
    "NOMA Shipping": 3.5,
    "Antonios": 4,
    "Dawn Accord": 2.5,
    "Outstanding Firepower": 5.5,
    "Sustained Combat": 5,
    "Strategy & Support": 5.5,
    "Fighter & Corvette": 6,
    "Projectile Weapon": 4.5,
    "Direct-Fire Weapon": 4
};

const data = [{
        name: "AT021",
        title: "Pulse Attacker",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Dawn Accord",
        direction: ["Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "AT021",
        title: "Tactical Attacker",
        img: "",
        type: "Fighter",
        variant: "B",
        variant_name: "Interference Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "AT021",
        title: "Heavy Attacker",
        img: "",
        type: "Fighter",
        variant: "C",
        variant_name: "Multi-Role Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "B192 Newland",
        title: "Heavy Attacker",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Multi-Role Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "BR050",
        title: "Standard Bomber",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "BR050",
        title: "Multi-Role Bomber",
        img: "",
        type: "Fighter",
        variant: "B",
        variant_name: "Defense Type",
        manufacturer: "Dawn Accord",
        direction: ["Sustained Combat", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "BR050",
        title: "Torpedo Bomber",
        img: "",
        type: "Fighter",
        variant: "C",
        variant_name: "Torpedo Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Balancer Anderson SC020",
        title: "Scout",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Interference Type",
        manufacturer: "Antonios",
        direction: ["Sustained Combat", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Bullfrog",
        title: "Dual-Purpose Bomber",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Siege Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Hayreddin's Loyal",
        title: "Pulsar Fighter",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Special Type",
        manufacturer: "Hayreddin Clan",
        direction: ["Outstanding Firepower", "Sustained Combat", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Janbiya Aer410",
        title: "Assault Attacker",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Mistral",
        title: "Combat Attacker",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Antonios",
        direction: ["Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "SC002",
        title: "Quantum Scout",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Generic Type",
        manufacturer: "Dawn Accord",
        direction: ["Sustained Combat", "Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Sandrake",
        title: "Atmospheric Interceptor",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Dual-Purpose Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Spore A404",
        title: "Light Fighter",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Stingray",
        title: "Torpedo Bomber",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Stealth Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Strix A100",
        title: "Joint Attacker",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "NOMA Shipping",
        direction: ["Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Vitas A021",
        title: "Heavy Attacker",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Vitas-B010",
        title: "Bomber",
        img: "",
        type: "Fighter",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Sustained Combat", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "CV-II003",
        title: "Light Corvette",
        img: "",
        type: "Corvette",
        variant: "A",
        variant_name: "Multi-Role Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "CV-M011",
        title: "Heavy Missile Corvette",
        img: "",
        type: "Corvette",
        variant: "A",
        variant_name: "Missile Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Sustained Combat", "Strategy & Support", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "CV-M011",
        title: "Heavy Cannon Corvette",
        img: "",
        type: "Corvette",
        variant: "B",
        variant_name: "Cannon Type",
        manufacturer: "Dawn Accord",
        direction: ["Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "CV-M011",
        title: "High-Speed Missile Corvette",
        img: "",
        type: "Corvette",
        variant: "C",
        variant_name: "High-Speed Type",
        manufacturer: "Dawn Accord",
        direction: ["Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "CV-T800",
        title: "Pulsar Corvette",
        img: "",
        type: "Corvette",
        variant: "A",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Strategy & Support", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Cellular Defender",
        title: "Heavy Torpedo Corvette",
        img: "",
        type: "Corvette",
        variant: "A",
        variant_name: "Multi-Role Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Nebula Chaser",
        title: "Heavy Corvette",
        img: "",
        type: "Corvette",
        variant: "A",
        variant_name: "Ballistic Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Nebula Chaser",
        title: "Pulsar Corvette",
        img: "",
        type: "Corvette",
        variant: "B",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "RedBeast 7-13",
        title: "Missile Corvette",
        img: "",
        type: "Corvette",
        variant: "A",
        variant_name: "Offensive Type",
        manufacturer: "NOMA Shipping",
        direction: ["Sustained Combat", "Strategy & Support", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "S-Levy 9",
        title: "Heavy Torpedo Escort Corvette",
        img: "",
        type: "Corvette",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Silent Assassin",
        title: "Armored Corvette",
        img: "",
        type: "Corvette",
        variant: "A",
        variant_name: "High-Speed Type",
        manufacturer: "NOMA Shipping",
        direction: ["Fighter & Corvette"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Void Elfin",
        title: "Stealth Missile Corvette",
        img: "",
        type: "Corvette",
        variant: "A",
        variant_name: "Offensive Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Sustained Combat", "Fighter & Corvette"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Carilion",
        title: "Recon Frigate",
        img: "",
        type: "Frigate",
        variant: "A",
        variant_name: "Recon Type",
        manufacturer: "Antonios",
        direction: ["Sustained Combat", "Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Carilion",
        title: "Heavy Cannon Frigate",
        img: "",
        type: "Frigate",
        variant: "B",
        variant_name: "Heavy Cannon Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Carilion",
        title: "Special Frigate",
        img: "",
        type: "Frigate",
        variant: "C",
        variant_name: "Special Type",
        manufacturer: "Antonios",
        direction: ["Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "FG300",
        title: "Multi-Role Frigate",
        img: "",
        type: "Frigate",
        variant: "A",
        variant_name: "Multi-Role Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "FG300",
        title: "Armored Frigate",
        img: "",
        type: "Frigate",
        variant: "B",
        variant_name: "Armored Type",
        manufacturer: "Dawn Accord",
        direction: ["Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "FG300",
        title: "Recon Frigate",
        img: "",
        type: "Frigate",
        variant: "C",
        variant_name: "Recon Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Mare Imbrium",
        title: "Assault Frigate",
        img: "",
        type: "Frigate",
        variant: "A",
        variant_name: "Railgun Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Mare Imbrium",
        title: "Experimental Pulse Cannon Frigate",
        img: "",
        type: "Frigate",
        variant: "B",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Mare Nubium",
        title: "Light Landing Ship",
        img: "",
        type: "Frigate",
        variant: "A",
        variant_name: "Assault Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Mare Nubium",
        title: "Anti-Aircraft Frigate",
        img: "",
        type: "Frigate",
        variant: "B",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Jupiter Industry",
        direction: ["Empty"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Mare Serenitatis",
        title: "Heavy Frigate",
        img: "",
        type: "Frigate",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Mare Serenitatis",
        title: "Missile Frigate",
        img: "",
        type: "Frigate",
        variant: "B",
        variant_name: "Missile Type",
        manufacturer: "Jupiter Industry",
        direction: ["Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Mare Serenitatis",
        title: "Anti-Aircraft Frigate",
        img: "",
        type: "Frigate",
        variant: "C",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Jupiter Industry",
        direction: ["Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Mare Tranquillitatis",
        title: "Missile Frigate",
        img: "",
        type: "Frigate",
        variant: "A",
        variant_name: "Integrated Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Mare Tranquillitatis",
        title: "Pulse Cannon Frigate",
        img: "",
        type: "Frigate",
        variant: "B",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Jupiter Industry",
        direction: ["Empty"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Mare Tranquillitatis",
        title: "Interceptor Frigate",
        img: "",
        type: "Frigate",
        variant: "C",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "NOMA M470",
        title: "Heavy Landing Ship",
        img: "",
        type: "Frigate",
        variant: "A",
        variant_name: "Siege Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower"],
        scope: "Empty",
        weight: 10
    }, {
        name: "NOMA M470",
        title: "Support Frigate",
        img: "",
        type: "Frigate",
        variant: "B",
        variant_name: "Support Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "NOMA M470",
        title: "Anti-Aircraft Frigate",
        img: "",
        type: "Frigate",
        variant: "C",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Reliat",
        title: "Rapid Torpedo Frigate",
        img: "",
        type: "Frigate",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Reliat",
        title: "Tactical Torpedo Frigate",
        img: "",
        type: "Frigate",
        variant: "B",
        variant_name: "Torpedo Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Reliat",
        title: "Stealth Frigate",
        img: "",
        type: "Frigate",
        variant: "C",
        variant_name: "Stealth Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Ruby",
        title: "Heavy Railgun Frigate",
        img: "",
        type: "Frigate",
        variant: "A",
        variant_name: "Railgun Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Ruby",
        title: "Experimental Ion Cannon Frigate",
        img: "",
        type: "Frigate",
        variant: "B",
        variant_name: "Ion Cannon Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Ruby",
        title: "Defensive Frigate",
        img: "",
        type: "Frigate",
        variant: "C",
        variant_name: "Defensive Type",
        manufacturer: "NOMA Shipping",
        direction: ["Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "XenoStinger",
        title: "Tactical Frigate",
        img: "",
        type: "Frigate",
        variant: "A",
        variant_name: "Special Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower"],
        scope: "Empty",
        weight: 5
    }, {
        name: "XenoStinger",
        title: "Defensive Frigate",
        img: "",
        type: "Frigate",
        variant: "B",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 5
    }, {
        name: "AC721",
        title: "Heavy Logistics Destroyer",
        img: "",
        type: "Destroyer",
        variant: "A",
        variant_name: "Generic Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "AC721",
        title: "Heavy Missile Destroyer",
        img: "",
        type: "Destroyer",
        variant: "B",
        variant_name: "Missile Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "AC721",
        title: "Heavy Dual-Purpose Assault Ship",
        img: "",
        type: "Destroyer",
        variant: "D",
        variant_name: "Aircraft Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Aldabra",
        title: "Heavy Cannon Destroyer",
        img: "",
        type: "Destroyer",
        variant: "A",
        variant_name: "Generic Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Aldabra",
        title: "Heavy Assault Destroyer",
        img: "",
        type: "Destroyer",
        variant: "B",
        variant_name: "Armored Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Ceres",
        title: "Aircraft Destroyer",
        img: "",
        type: "Destroyer",
        variant: "A",
        variant_name: "Aircraft Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Ceres",
        title: "Support Destroyer",
        img: "",
        type: "Destroyer",
        variant: "B",
        variant_name: "Support Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Ceres",
        title: "Tactical Destroyer",
        img: "",
        type: "Destroyer",
        variant: "C",
        variant_name: "Tactical Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Eris I",
        title: "Maneuver Assault Destroyer",
        img: "",
        type: "Destroyer",
        variant: "A",
        variant_name: "Cannon Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Eris I",
        title: "Heavy Cannon Destroyer",
        img: "",
        type: "Destroyer",
        variant: "B",
        variant_name: "Heavy Cannon Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Eris I",
        title: "Armored Destroyer",
        img: "",
        type: "Destroyer",
        variant: "C",
        variant_name: "Armored Type",
        manufacturer: "Jupiter Industry",
        direction: ["Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Guardian",
        title: "Support Destroyer",
        img: "",
        type: "Destroyer",
        variant: "A",
        variant_name: "Support Type",
        manufacturer: "Antonios",
        direction: ["Empty"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Guardian",
        title: "Dual-Purpose Assault Ship",
        img: "",
        type: "Destroyer",
        variant: "B",
        variant_name: "Dual-Purpose Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Guardian",
        title: "Experimental Pulse Assault Ship",
        img: "",
        type: "Destroyer",
        variant: "C",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Quaoar",
        title: "Railgun Destroyer",
        img: "",
        type: "Destroyer",
        variant: "A",
        variant_name: "Railgun Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "Quaoar",
        title: "Torpedo Destroyer",
        img: "",
        type: "Destroyer",
        variant: "B",
        variant_name: "Torpedo Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Taurus",
        title: "Pulse Cannon Destroyer",
        img: "",
        type: "Destroyer",
        variant: "A",
        variant_name: "Offensive Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Taurus",
        title: "Assault Destroyer",
        img: "",
        type: "Destroyer",
        variant: "B",
        variant_name: "Assault Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Taurus",
        title: "Defensive Destroyer",
        img: "",
        type: "Destroyer",
        variant: "C",
        variant_name: "Defensive Type",
        manufacturer: "NOMA Shipping",
        direction: ["Sustained Combat", "Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Tundra",
        title: "Tactical Destroyer",
        img: "",
        type: "Destroyer",
        variant: "A",
        variant_name: "Support Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Tundra",
        title: "Aircraft Destroyer",
        img: "",
        type: "Destroyer",
        variant: "B",
        variant_name: "Aircraft Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Winged Hussar",
        title: "Light Missile Destroyer",
        img: "",
        type: "Destroyer",
        variant: "A",
        variant_name: "Anti-Ship Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Winged Hussar",
        title: "Integrated Missile Destroyer",
        img: "",
        type: "Destroyer",
        variant: "B",
        variant_name: "Integrated Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "Winged Hussar",
        title: "Area-Denial Anti-Aircraft Destroyer",
        img: "",
        type: "Destroyer",
        variant: "C",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Antonios",
        direction: ["Sustained Combat", "Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "CAS066",
        title: "Generic Cruiser",
        img: "",
        type: "Cruiser",
        variant: "A",
        variant_name: "Integrated Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "CAS066",
        title: "Artillery Cruiser",
        img: "",
        type: "Cruiser",
        variant: "B",
        variant_name: "Artillery Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "CAS066",
        title: "Aircraft Cruiser",
        img: "",
        type: "Cruiser",
        variant: "C",
        variant_name: "Aircraft Type",
        manufacturer: "Dawn Accord",
        direction: ["Empty"],
        scope: "Empty",
        weight: 10
    }, {
        name: "CAS066",
        title: "Auxiliary Cruiser",
        img: "",
        type: "Cruiser",
        variant: "D",
        variant_name: "Support Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Callisto",
        title: "Cluster Torpedo Raid Ship",
        img: "",
        type: "Cruiser",
        variant: "A",
        variant_name: "Torpedo Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 2
    }, {
        name: "Callisto",
        title: "Heavy Torpedo Raid Ship",
        img: "",
        type: "Cruiser",
        variant: "B",
        variant_name: "Anti-Ship Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 2
    }, {
        name: "Callisto",
        title: "Heavy UAV Cruiser",
        img: "",
        type: "Cruiser",
        variant: "C",
        variant_name: "Support Type",
        manufacturer: "Jupiter Industry",
        direction: ["Empty"],
        scope: "Projectile Weapon",
        weight: 2
    }, {
        name: "Chimera",
        title: "Heavy Cruiser",
        img: "",
        type: "Cruiser",
        variant: "A",
        variant_name: "Ballistic Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Chimera",
        title: "Cannon Cruiser",
        img: "",
        type: "Cruiser",
        variant: "B",
        variant_name: "Heavy Cannon Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Chimera",
        title: "Defensive Cruiser",
        img: "",
        type: "Cruiser",
        variant: "C",
        variant_name: "Defensive Type",
        manufacturer: "NOMA Shipping",
        direction: ["Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Conamara Chaos",
        title: "Railgun Cruiser",
        img: "",
        type: "Cruiser",
        variant: "A",
        variant_name: "Railgun Type",
        manufacturer: "Jupiter Industry",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Conamara Chaos",
        title: "High-Speed Plasma Cruiser",
        img: "",
        type: "Cruiser",
        variant: "B",
        variant_name: "Plasma Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Io",
        title: "Assault Ion Cannon Cruiser",
        img: "",
        type: "Cruiser",
        variant: "A",
        variant_name: "Ion Cannon Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Io",
        title: "High-Speed Ion Cannon Cruiser",
        img: "",
        type: "Cruiser",
        variant: "B",
        variant_name: "Anti-Ship Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Io",
        title: "Siege Ion Cannon Cruiser",
        img: "",
        type: "Cruiser",
        variant: "C",
        variant_name: "Siege Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Jaeger",
        title: "Heavy Aircraft Cruiser",
        img: "",
        type: "Cruiser",
        variant: "A",
        variant_name: "Support Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 5
    }, {
        name: "Jaeger",
        title: "Heavy Cannon Cruiser",
        img: "",
        type: "Cruiser",
        variant: "B",
        variant_name: "Anti-Ship Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "KCCPV2.0",
        title: "Light Attack Cruiser",
        img: "",
        type: "Cruiser",
        variant: "A",
        variant_name: "Integrated Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower", "Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 10
    }, {
        name: "KCCPV2.0",
        title: "Light Pulse Attack Cruiser",
        img: "",
        type: "Cruiser",
        variant: "B",
        variant_name: "Pulse Cannon Type",
        manufacturer: "Dawn Accord",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "KCCPV2.0",
        title: "Light Railgun Cruiser",
        img: "",
        type: "Cruiser",
        variant: "C",
        variant_name: "Railgun Type",
        manufacturer: "Dawn Accord",
        direction: ["Empty"],
        scope: "Direct-Fire Weapon",
        weight: 10
    }, {
        name: "KCCPV2.0",
        title: "Light Aircraft Cruiser",
        img: "",
        type: "Cruiser",
        variant: "D",
        variant_name: "Aircraft Type",
        manufacturer: "Dawn Accord",
        direction: ["Empty"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Light Cone",
        title: "Multi-Role Missile Cruiser Cruiser",
        img: "",
        type: "Cruiser",
        variant: "A",
        variant_name: "Generic Type",
        manufacturer: "NOMA Shipping",
        direction: ["Empty"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Light Cone",
        title: "Area-Denial Anti-Aircraft Cruiser",
        img: "",
        type: "Cruiser",
        variant: "B",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Light Cone",
        title: "Offensive Missile Cruiser",
        img: "",
        type: "Cruiser",
        variant: "C",
        variant_name: "Assault Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower"],
        scope: "Projectile Weapon",
        weight: 5
    }, {
        name: "Predator",
        title: "Aircraft Cruiser",
        img: "",
        type: "Cruiser",
        variant: "A",
        variant_name: "Generic Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Predator",
        title: "Tactical Aircraft Cruiser",
        img: "",
        type: "Cruiser",
        variant: "B",
        variant_name: "Tactical Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Predator",
        title: "Anti-Aircraft Cruiser",
        img: "",
        type: "Cruiser",
        variant: "C",
        variant_name: "Anti-Aircraft Type",
        manufacturer: "Antonios",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 10
    }, {
        name: "Constantine the Great",
        title: "Multi-Role Battlecruiser",
        img: "",
        type: "Battlecruiser",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 2
    }, {
        name: "Eternal Storm",
        title: "Attack Battlecruiser",
        img: "",
        type: "Battlecruiser",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Jupiter Industry",
        direction: ["Outstanding Firepower"],
        scope: "Direct-Fire Weapon",
        weight: 2
    }, {
        name: "ST59",
        title: "Defensive Battlecruiser",
        img: "",
        type: "Battlecruiser",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Dawn Accord",
        direction: ["Sustained Combat", "Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 5
    }, {
        name: "Spear of Uranus",
        title: "Heavy Battlecruiser",
        img: "",
        type: "Battlecruiser",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Sustained Combat"],
        scope: "Direct-Fire Weapon",
        weight: 2
    }, {
        name: "Thunderbolt Star",
        title: "Multi-Role Arsenal Ship",
        img: "",
        type: "Battlecruiser",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Thunderbolt Group",
        direction: ["Outstanding Firepower", "Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 2
    }, {
        name: "Ediacaran",
        title: "Heavy Firepower Auxiliary Ship",
        img: "",
        type: "Auxiliary Ship",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "NOMA Shipping",
        direction: ["Outstanding Firepower", "Strategy & Support"],
        scope: "Empty",
        weight: 2
    }, {
        name: "FSV830",
        title: "Fast Tactical Auxiliary Ship",
        img: "",
        type: "Auxiliary Ship",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Dawn Accord",
        direction: ["Sustained Combat", "Strategy & Support"],
        scope: "Empty",
        weight: 5
    }, {
        name: "CV3000",
        title: "High-Speed Carrier",
        img: "",
        type: "Carrier",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Dawn Accord",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 2
    }, {
        name: "Marshal Crux",
        title: "Carrier",
        img: "",
        type: "Carrier",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "Antonios",
        direction: ["Outstanding Firepower", "Strategy & Support"],
        scope: "Direct-Fire Weapon",
        weight: 2
    }, {
        name: "Solar Whale",
        title: "Armed Tactical Carrier",
        img: "",
        type: "Carrier",
        variant: "A",
        variant_name: "Super Type",
        manufacturer: "NOMA Shipping",
        direction: ["Strategy & Support"],
        scope: "Empty",
        weight: 2
    }
];

export { difficulty, data };
