
export type RegularShip = {
    name: string;
    title: string;
    img: string;
    type: "Small Fighter" | "Medium Fighter" | "Large Fighter" | "Corvette" | "Frigate" | "Destroyer" | "Cruiser" | "Battlecruiser" | "Auxiliary Ship" | "Carrier";
    variant: "A" | "B" | "C" | "D";
    variant_name: string;
    command_points: null | number;
    aircraft_space: null | number;
    aircraft_capacity: null | number;
    aircraft_type?: string[];
    row: "Front Row" | "Middle Row" | "Back Row";
    flagship: null | string[];
    hitpoints: number;
    antiship: null | number;
    antiair: null | number;
    siege: null | number;
    cruise_speed: null | number;
    warp_speed: null | number;
    maxCount: number;
    storage: null | number;
}

export type SuperCapitalShip = {
    name: string;
    title: string;
    img: string;
    type: "Small Fighter" | "Medium Fighter" | "Large Fighter" | "Corvette" | "Frigate" | "Destroyer" | "Cruiser" | "Battlecruiser" | "Auxiliary Ship" | "Carrier";
    variant: "A" | "B" | "C" | "D";
    variant_name: string;
    command_points: number;
    row: "Front Row" | "Middle Row" | "Back Row";
    flagship: null | string[];
    hitpoints: number;
    cruise_speed: null | number;
    warp_speed: null | number;
    maxCount: number;
    storage: null | number;
    modules: (MiscMod | WeaponMod | AircraftMod)[];
}

export type MiscMod = {
    name: string;
}

export type WeaponMod = {
    name: string;
    antiship: null | number;
    antiair: null | number;
    siege: null | number;
}

export type AircraftMod = {
    name: string;
    aircraft_capacity: number;
    aircraft_type: ("Small Fighter" | "Medium Fighter" | "Large Fighter" | "Corvette")[];
}

const data: (RegularShip | SuperCapitalShip)[] = [{
    name: "AT021",
    title: "Pulse Attacker",
    img: "/ships/at021_a.png",
    type: "Medium Fighter",
    variant: "A",
    variant_name: "Pulse Cannon Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 4920,
    antiship: 1482,
    antiair: 888,
    siege: 42,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 15,
    storage: null,
}, {
    name: "AT021",
    title: "Tactical Attacker",
    img: "/ships/at021_b.png",
    type: "Medium Fighter",
    variant: "B",
    variant_name: "Interference Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 4920,
    antiship: 843,
    antiair: 675,
    siege: 96,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 15,
    storage: null,
}, {
    name: "AT021",
    title: "Heavy Attacker",
    img: "/ships/at021_c.png",
    type: "Medium Fighter",
    variant: "C",
    variant_name: "Multi-Role Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 4920,
    antiship: 3366,
    antiair: null,
    siege: 387,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 15,
    storage: null,
}, {
    name: "B192 Newland",
    title: "Heavy Attacker",
    img: "/ships/b192newland.png",
    type: "Medium Fighter",
    variant: "A",
    variant_name: "Multi-Role Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 4680,
    antiship: 1284,
    antiair: 1080,
    siege: 270,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "BR050",
    title: "Standard Bomber",
    img: "/ships/br050_a.png",
    type: "Large Fighter",
    variant: "A",
    variant_name: "Anti-Ship Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 5040,
    antiship: 3770,
    antiair: null,
    siege: 1350,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "BR050",
    title: "Multi-Role Bomber",
    img: "/ships/br050_b.png",
    type: "Large Fighter",
    variant: "B",
    variant_name: "Defense Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 5040,
    antiship: 2514,
    antiair: null,
    siege: 900,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "BR050",
    title: "Torpedo Bomber",
    img: "/ships/br050_c.png",
    type: "Large Fighter",
    variant: "C",
    variant_name: "Torpedo Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 5040,
    antiship: 642,
    antiair: null,
    siege: 254,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Balancer Anderson SC020",
    title: "Scout",
    img: "/ships/sc020.png",
    type: "Small Fighter",
    variant: "A",
    variant_name: "Interference Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 3450,
    antiship: 150,
    antiair: 860,
    siege: null,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Bullfrog",
    title: "Dual-Purpose Bomber",
    img: "/ships/bullfrog.png",
    type: "Large Fighter",
    variant: "A",
    variant_name: "Siege Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 4740,
    antiship: 1920,
    antiair: null,
    siege: 880,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Hayreddin's Loyal",
    title: "Pulsar Fighter",
    img: "/ships/hayreddinsLoyal.png",
    type: "Medium Fighter",
    variant: "A",
    variant_name: "Special Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 6480,
    antiship: 4614,
    antiair: 2214,
    siege: 1521,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 8,
    storage: null,
}, {
    name: "Janbiya Aer410",
    title: "Assault Attacker",
    img: "/ships/janbiyaAer410.png",
    type: "Medium Fighter",
    variant: "A",
    variant_name: "Anti-Ship Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 4050,
    antiship: 1416,
    antiair: 1194,
    siege: 246,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Mistral",
    title: "Combat Attacker",
    img: "/ships/mistral.png",
    type: "Medium Fighter",
    variant: "A",
    variant_name: "Anti-Aircraft Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 5400,
    antiship: 220,
    antiair: 2124,
    siege: null,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "SC002",
    title: "Quantum Scout",
    img: "/ships/sc002.png",
    type: "Small Fighter",
    variant: "A",
    variant_name: "Generic Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 2850,
    antiship: 700,
    antiair: 700,
    siege: null,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 15,
    storage: null,
}, {
    name: "Sandrake",
    title: "Atmospheric Interceptor",
    img: "/ships/sandrake.png",
    type: "Small Fighter",
    variant: "A",
    variant_name: "Dual-Purpose Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 4200,
    antiship: 120,
    antiair: 2685,
    siege: 0,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Spore A404",
    title: "Light Fighter",
    img: "/ships/sporeA404.png",
    type: "Small Fighter",
    variant: "A",
    variant_name: "Anti-Aircraft Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 3550,
    antiship: 135,
    antiair: 1990,
    siege: null,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Stingray",
    title: "Torpedo Bomber",
    img: "/ships/stingray.png",
    type: "Large Fighter",
    variant: "A",
    variant_name: "Stealth Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 5200,
    antiship: 3120,
    antiair: null,
    siege: 992,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Strix A100",
    title: "Joint Attacker",
    img: "/ships/strixA100.png",
    type: "Medium Fighter",
    variant: "A",
    variant_name: "Anti-Ship Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 4920,
    antiship: 1989,
    antiair: 1377,
    siege: 396,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Vitas A021",
    title: "Heavy Attacker",
    img: "/ships/vitasA021.png",
    type: "Medium Fighter",
    variant: "A",
    variant_name: "Anti-Ship Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 5370,
    antiship: 2613,
    antiair: 540,
    siege: 543,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Vitas-B010",
    title: "Bomber",
    img: "/ships/vitasB010.png",
    type: "Large Fighter",
    variant: "A",
    variant_name: "Anti-Ship Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 5860,
    antiship: 4588,
    antiair: null,
    siege: 1696,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "CV-II003",
    title: "Light Corvette",
    img: "/ships/cvii003.png",
    type: "Corvette",
    variant: "A",
    variant_name: "Multi-Role Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 4900,
    antiship: 1880,
    antiair: 144,
    siege: 418,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 15,
    storage: null,
}, {
    name: "CV-M011",
    title: "Heavy Missile Corvette",
    img: "/ships/cvm011_a.png",
    type: "Corvette",
    variant: "A",
    variant_name: "Missile Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 7500,
    antiship: 2187,
    antiair: 837,
    siege: 240,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 15,
    storage: null,
}, {
    name: "CV-M011",
    title: "Heavy Cannon Corvette",
    img: "/ships/cvm011_b.png",
    type: "Corvette",
    variant: "B",
    variant_name: "Cannon Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 7500,
    antiship: 2315,
    antiair: 837,
    siege: 282,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 15,
    storage: null,
}, {
    name: "CV-M011",
    title: "High-Speed Missile Corvette",
    img: "/ships/cvm011_c.png",
    type: "Corvette",
    variant: "C",
    variant_name: "High-Speed Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 7500,
    antiship: 1206,
    antiair: 1008,
    siege: 130,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 15,
    storage: null,
}, {
    name: "CV-T800",
    title: "Pulsar Corvette",
    img: "/ships/cvt800.png",
    type: "Corvette",
    variant: "A",
    variant_name: "Anti-Aircraft Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 7500,
    antiship: 2400,
    antiair: 1920,
    siege: 48,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 15,
    storage: null,
}, {
    name: "Cellular Defender",
    title: "Heavy Torpedo Corvette",
    img: "/ships/cellularDefender.png",
    type: "Corvette",
    variant: "A",
    variant_name: "Multi-Role Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 6650,
    antiship: 4740,
    antiair: 1159,
    siege: 1656,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Nebula Chaser",
    title: "Heavy Corvette",
    img: "/ships/nebulaChaser_a.png",
    type: "Corvette",
    variant: "A",
    variant_name: "Ballistic Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 6300,
    antiship: 2400,
    antiair: 547,
    siege: 588,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Nebula Chaser",
    title: "Pulsar Corvette",
    img: "/ships/nebulaChaser_b.png",
    type: "Corvette",
    variant: "B",
    variant_name: "Pulse Cannon Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 5400,
    antiship: 3680,
    antiair: 2208,
    siege: 73,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "RedBeast 7-13",
    title: "Missile Corvette",
    img: "/ships/redbeast713.png",
    type: "Corvette",
    variant: "A",
    variant_name: "Offensive Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 5200,
    antiship: 2520,
    antiair: 360,
    siege: 184,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "S-Levy 9",
    title: "Heavy Torpedo Escort Corvette",
    img: "/ships/slevy9.png",
    type: "Corvette",
    variant: "A",
    variant_name: "Anti-Ship Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 6000,
    antiship: 3870,
    antiair: null,
    siege: 1820,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Silent Assassin",
    title: "Armored Corvette",
    img: "/ships/silentAssassin.png",
    type: "Corvette",
    variant: "A",
    variant_name: "High-Speed Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 5350,
    antiship: 1800,
    antiair: null,
    siege: 630,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Void Elfin",
    title: "Stealth Missile Corvette",
    img: "/ships/voidElfin.png",
    type: "Corvette",
    variant: "A",
    variant_name: "Offensive Type",
    command_points: null,
    aircraft_space: 1,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: null,
    hitpoints: 5200,
    antiship: 3593,
    antiair: 468,
    siege: 315,
    cruise_speed: null,
    warp_speed: null,
    maxCount: 10,
    storage: null,
}, {
    name: "Carilion",
    title: "Recon Frigate",
    img: "/ships/carilion_a.png",
    type: "Frigate",
    variant: "A",
    variant_name: "Recon Type",
    command_points: 4,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 8340,
    antiship: 1125,
    antiair: 361,
    siege: 315,
    cruise_speed: 1040,
    warp_speed: 5200,
    maxCount: 10,
    storage: 1800,
}, {
    name: "Carilion",
    title: "Heavy Cannon Frigate",
    img: "/ships/carilion_b.png",
    type: "Frigate",
    variant: "B",
    variant_name: "Heavy Cannon Type",
    command_points: 5,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire", "Combat Insertion"],
    hitpoints: 9840,
    antiship: 2485,
    antiair: 96,
    siege: 540,
    cruise_speed: 950,
    warp_speed: 4750,
    maxCount: 10,
    storage: 1500,
}, {
    name: "Carilion",
    title: "Special Frigate",
    img: "/ships/carilion_c.png",
    type: "Frigate",
    variant: "C",
    variant_name: "Special Type",
    command_points: 5,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 8340,
    antiship: 1125,
    antiair: 361,
    siege: 315,
    cruise_speed: 1040,
    warp_speed: 5200,
    maxCount: 10,
    storage: 1200,
}, {
    name: "FG300",
    title: "Multi-Role Frigate",
    img: "/ships/fg300_a.png",
    type: "Frigate",
    variant: "A",
    variant_name: "Multi-Role Type",
    command_points: 3,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 10530,
    antiship: 1157,
    antiair: 607,
    siege: 270,
    cruise_speed: 1000,
    warp_speed: 5000,
    maxCount: 15,
    storage: 2000,
}, {
    name: "FG300",
    title: "Armored Frigate",
    img: "/ships/fg300_b.png",
    type: "Frigate",
    variant: "B",
    variant_name: "Armored Type",
    command_points: 3,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 12540,
    antiship: 771,
    antiair: 678,
    siege: 180,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 15,
    storage: 1500,
}, {
    name: "FG300",
    title: "Recon Frigate",
    img: "/ships/fg300_c.png",
    type: "Frigate",
    variant: "C",
    variant_name: "Recon Type",
    command_points: 3,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 12540,
    antiship: 385,
    antiair: 505,
    siege: 90,
    cruise_speed: 1040,
    warp_speed: 5200,
    maxCount: 15,
    storage: 2200,
}, {
    name: "Mare Imbrium",
    title: "Assault Frigate",
    img: "/ships/mareImbrium_a.png",
    type: "Frigate",
    variant: "A",
    variant_name: "Railgun Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire", "Guerrilla Combat Insertion"],
    hitpoints: 14480,
    antiship: 3130,
    antiair: 240,
    siege: 773,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 10,
    storage: 1800,
}, {
    name: "Mare Imbrium",
    title: "Experimental Pulse Cannon Frigate",
    img: "/ships/mareImbrium_b.png",
    type: "Frigate",
    variant: "B",
    variant_name: "Pulse Cannon Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire", "Guerrilla Combat Insertion"],
    hitpoints: 14480,
    antiship: 3933,
    antiair: 496,
    siege: 275,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 10,
    storage: 1800,
}, {
    name: "Mare Nubium",
    title: "Light Landing Ship",
    img: "/ships/mareNubium_a.png",
    type: "Frigate",
    variant: "A",
    variant_name: "Assault Type",
    command_points: 4,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 9030,
    antiship: 953,
    antiair: null,
    siege: 1532,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 10,
    storage: 1700,
}, {
    name: "Mare Nubium",
    title: "Anti-Aircraft Frigate",
    img: "/ships/mareNubium_b.png",
    type: "Frigate",
    variant: "B",
    variant_name: "Anti-Aircraft Type",
    command_points: 4,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 9030,
    antiship: 685,
    antiair: 3008,
    siege: null,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 10,
    storage: 1800,
}, {
    name: "Mare Serenitatis",
    title: "Heavy Frigate",
    img: "/ships/mareSerenitatis_a.png",
    type: "Frigate",
    variant: "A",
    variant_name: "Anti-Ship Type",
    command_points: 5,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 14970,
    antiship: 3385,
    antiair: 199,
    siege: 951,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 10,
    storage: 2000,
}, {
    name: "Mare Serenitatis",
    title: "Missile Frigate",
    img: "/ships/mareSerenitatis_b.png",
    type: "Frigate",
    variant: "B",
    variant_name: "Missile Type",
    command_points: 5,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 14970,
    antiship: 2300,
    antiair: 199,
    siege: 298,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 10,
    storage: 1800,
}, {
    name: "Mare Serenitatis",
    title: "Anti-Aircraft Frigate",
    img: "/ships/mareSerenitatis_c.png",
    type: "Frigate",
    variant: "C",
    variant_name: "Anti-Aircraft Type",
    command_points: 5,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 14970,
    antiship: 780,
    antiair: 967,
    siege: null,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 10,
    storage: 2200,
}, {
    name: "Mare Tranquillitatis",
    title: "Missile Frigate",
    img: "/ships/mareTranquillitatis_a.png",
    type: "Frigate",
    variant: "A",
    variant_name: "Integrated Type",
    command_points: 4,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 12360,
    antiship: 1896,
    antiair: 811,
    siege: 328,
    cruise_speed: 1000,
    warp_speed: 5000,
    maxCount: 10,
    storage: 1800,
}, {
    name: "Mare Tranquillitatis",
    title: "Pulse Cannon Frigate",
    img: "/ships/mareTranquillitatis_b.png",
    type: "Frigate",
    variant: "B",
    variant_name: "Pulse Cannon Type",
    command_points: 4,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 12360,
    antiship: 1125,
    antiair: 1126,
    siege: 148,
    cruise_speed: 1000,
    warp_speed: 5000,
    maxCount: 10,
    storage: 1500,
}, {
    name: "Mare Tranquillitatis",
    title: "Interceptor Frigate",
    img: "/ships/mareTranquillitatis_c.png",
    type: "Frigate",
    variant: "C",
    variant_name: "Anti-Aircraft Type",
    command_points: 4,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire", "Anti-Aircraft Network I", "Fast Switching"],
    hitpoints: 12360,
    antiship: 535,
    antiair: 944,
    siege: 120,
    cruise_speed: 1000,
    warp_speed: 5000,
    maxCount: 10,
    storage: 2000,
}, {
    name: "NOMA M470",
    title: "Heavy Landing Ship",
    img: "/ships/nomaM470_a.png",
    type: "Frigate",
    variant: "A",
    variant_name: "Siege Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 14000,
    antiship: 296,
    antiair: 72,
    siege: 1650,
    cruise_speed: 800,
    warp_speed: 4000,
    maxCount: 10,
    storage: 2200,
}, {
    name: "NOMA M470",
    title: "Support Frigate",
    img: "/ships/nomaM470_b.png",
    type: "Frigate",
    variant: "B",
    variant_name: "Support Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 14000,
    antiship: 200,
    antiair: 72,
    siege: 138,
    cruise_speed: 800,
    warp_speed: 4000,
    maxCount: 10,
    storage: 2000,
}, {
    name: "NOMA M470",
    title: "Anti-Aircraft Frigate",
    img: "/ships/nomaM470_c.png",
    type: "Frigate",
    variant: "C",
    variant_name: "Anti-Aircraft Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 14000,
    antiship: 200,
    antiair: 2376,
    siege: 138,
    cruise_speed: 800,
    warp_speed: 4000,
    maxCount: 10,
    storage: 2000,
}, {
    name: "Reliat",
    title: "Rapid Torpedo Frigate",
    img: "/ships/reliat_a.png",
    type: "Frigate",
    variant: "A",
    variant_name: "Anti-Ship Type",
    command_points: 4,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 10530,
    antiship: 2072,
    antiair: 411,
    siege: 330,
    cruise_speed: 800,
    warp_speed: 4000,
    maxCount: 10,
    storage: 2000,
}, {
    name: "Reliat",
    title: "Tactical Torpedo Frigate",
    img: "/ships/reliat_b.png",
    type: "Frigate",
    variant: "B",
    variant_name: "Torpedo Type",
    command_points: 4,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 10530,
    antiship: 3088,
    antiair: 86,
    siege: 874,
    cruise_speed: 800,
    warp_speed: 4000,
    maxCount: 10,
    storage: 1800,
}, {
    name: "Reliat",
    title: "Stealth Frigate",
    img: "/ships/reliat_c.png",
    type: "Frigate",
    variant: "C",
    variant_name: "Stealth Type",
    command_points: 4,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 10530,
    antiship: 3257,
    antiair: null,
    siege: 205,
    cruise_speed: 800,
    warp_speed: 4000,
    maxCount: 10,
    storage: 1500,
}, {
    name: "Ruby",
    title: "Heavy Railgun Frigate",
    img: "/ships/ruby_a.png",
    type: "Frigate",
    variant: "A",
    variant_name: "Railgun Type",
    command_points: 5,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 16520,
    antiship: 3172,
    antiair: 75,
    siege: 658,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 10,
    storage: 1200,
}, {
    name: "Ruby",
    title: "Experimental Ion Cannon Frigate",
    img: "/ships/ruby_b.png",
    type: "Frigate",
    variant: "B",
    variant_name: "Ion Cannon Type",
    command_points: 5,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 14970,
    antiship: 4743,
    antiair: 571,
    siege: 711,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 10,
    storage: 1000,
}, {
    name: "Ruby",
    title: "Defensive Frigate",
    img: "/ships/ruby_c.png",
    type: "Frigate",
    variant: "C",
    variant_name: "Defensive Type",
    command_points: 5,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 17550,
    antiship: 1632,
    antiair: null,
    siege: 656,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 10,
    storage: 1400,
}, {
    name: "XenoStinger",
    title: "Tactical Frigate",
    img: "/ships/xenostinger_a.png",
    type: "Frigate",
    variant: "A",
    variant_name: "Special Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 10530,
    antiship: 5840,
    antiair: 86,
    siege: 1148,
    cruise_speed: 800,
    warp_speed: 4000,
    maxCount: 10,
    storage: 1200,
}, {
    name: "XenoStinger",
    title: "Defensive Frigate",
    img: "/ships/xenostinger_b.png",
    type: "Frigate",
    variant: "B",
    variant_name: "Anti-Aircraft Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 10530,
    antiship: 240,
    antiair: 2426,
    siege: 28,
    cruise_speed: 800,
    warp_speed: 4000,
    maxCount: 10,
    storage: 1200,
}, {
    name: "AC721",
    title: "Heavy Logistics Destroyer",
    img: "/ships/ac721_a.png",
    type: "Destroyer",
    variant: "A",
    variant_name: "Generic Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire", "Optimized Reload I"],
    hitpoints: 34140,
    antiship: 1800,
    antiair: 390,
    siege: 408,
    cruise_speed: 800,
    warp_speed: 4000,
    maxCount: 15,
    storage: 18000,
}, {
    name: "AC721",
    title: "Heavy Missile Destroyer",
    img: "/ships/ac721_b.png",
    type: "Destroyer",
    variant: "B",
    variant_name: "Missile Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 34140,
    antiship: 3300,
    antiair: 780,
    siege: 345,
    cruise_speed: 800,
    warp_speed: 4000,
    maxCount: 15,
    storage: 13000,
}, {
    name: "AC721",
    title: "Heavy Dual-Purpose Assault Ship",
    img: "/ships/ac721_d.png",
    type: "Destroyer",
    variant: "D",
    variant_name: "Aircraft Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: 2,
    aircraft_type: ["Corvette"],
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 30730,
    antiship: 1200,
    antiair: 228,
    siege: 181,
    cruise_speed: 800,
    warp_speed: 4000,
    maxCount: 15,
    storage: 11500,
}, {
    name: "Aldabra",
    title: "Heavy Cannon Destroyer",
    img: "/ships/aldabra_a.png",
    type: "Destroyer",
    variant: "A",
    variant_name: "Generic Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 37090,
    antiship: 5820,
    antiair: 921,
    siege: 775,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 10,
    storage: 7000,
}, {
    name: "Aldabra",
    title: "Heavy Assault Destroyer",
    img: "/ships/aldabra_b.png",
    type: "Destroyer",
    variant: "B",
    variant_name: "Armored Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 40799,
    antiship: 5280,
    antiair: 540,
    siege: 1048,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 10,
    storage: 7000,
}, {
    name: "Ceres",
    title: "Aircraft Destroyer",
    img: "/ships/ceres_a.png",
    type: "Destroyer",
    variant: "A",
    variant_name: "Aircraft Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: 2,
    aircraft_type: ["Small Fighter", "Medium Fighter"],
    row: "Back Row",
    flagship: ["Focus Fire", "Strategic Strike I"],
    hitpoints: 32310,
    antiship: 1500,
    antiair: 216,
    siege: 252,
    cruise_speed: 850,
    warp_speed: 4250,
    maxCount: 10,
    storage: 10000,
}, {
    name: "Ceres",
    title: "Support Destroyer",
    img: "/ships/ceres_b.png",
    type: "Destroyer",
    variant: "B",
    variant_name: "Support Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 32310,
    antiship: 1500,
    antiair: 3096,
    siege: 252,
    cruise_speed: 850,
    warp_speed: 4250,
    maxCount: 10,
    storage: 9000,
}, {
    name: "Ceres",
    title: "Tactical Destroyer",
    img: "/ships/ceres_c.png",
    type: "Destroyer",
    variant: "C",
    variant_name: "Tactical Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 32310,
    antiship: 1500,
    antiair: 216,
    siege: 252,
    cruise_speed: 850,
    warp_speed: 4250,
    maxCount: 10,
    storage: 9000,
}, {
    name: "Eris I",
    title: "Maneuver Assault Destroyer",
    img: "/ships/eris_a.png",
    type: "Destroyer",
    variant: "A",
    variant_name: "Cannon Type",
    command_points: 7,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire", "Cautious Warning"],
    hitpoints: 30540,
    antiship: 4500,
    antiair: 270,
    siege: 350,
    cruise_speed: 900,
    warp_speed: 4500,
    maxCount: 10,
    storage: 9000,
}, {
    name: "Eris I",
    title: "Heavy Cannon Destroyer",
    img: "/ships/eris_b.png",
    type: "Destroyer",
    variant: "B",
    variant_name: "Heavy Cannon Type",
    command_points: 7,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 30540,
    antiship: 4963,
    antiair: 252,
    siege: 1239,
    cruise_speed: 850,
    warp_speed: 4250,
    maxCount: 10,
    storage: 8500,
}, {
    name: "Eris I",
    title: "Armored Destroyer",
    img: "/ships/eris_c.png",
    type: "Destroyer",
    variant: "C",
    variant_name: "Armored Type",
    command_points: 7,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire", "Patrolling Defense"],
    hitpoints: 35140,
    antiship: 4500,
    antiair: 270,
    siege: 350,
    cruise_speed: 850,
    warp_speed: 4250,
    maxCount: 10,
    storage: 9500,
}, {
    name: "Guardian",
    title: "Support Destroyer",
    img: "/ships/guardian_a.png",
    type: "Destroyer",
    variant: "A",
    variant_name: "Support Type",
    command_points: 9,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire", "Strategic Strike I"],
    hitpoints: 25650,
    antiship: 3054,
    antiair: 3500,
    siege: 349,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 10,
    storage: 10000,
}, {
    name: "Guardian",
    title: "Dual-Purpose Assault Ship",
    img: "/ships/guardian_b.png",
    type: "Destroyer",
    variant: "B",
    variant_name: "Dual-Purpose Type",
    command_points: 9,
    aircraft_space: null,
    aircraft_capacity: 2,
    aircraft_type: ["Corvette"],
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 25650,
    antiship: 3054,
    antiair: 1196,
    siege: 349,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 10,
    storage: 9500,
}, {
    name: "Guardian",
    title: "Experimental Pulse Assault Ship",
    img: "/ships/guardian_c.png",
    type: "Destroyer",
    variant: "C",
    variant_name: "Pulse Cannon Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 25650,
    antiship: 6210,
    antiair: 248,
    siege: 400,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 10,
    storage: 8500,
}, {
    name: "Quaoar",
    title: "Railgun Destroyer",
    img: "/ships/quaoar_a.png",
    type: "Destroyer",
    variant: "A",
    variant_name: "Railgun Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 30540,
    antiship: 4800,
    antiair: 216,
    siege: 506,
    cruise_speed: 850,
    warp_speed: 4250,
    maxCount: 10,
    storage: 8500,
}, {
    name: "Quaoar",
    title: "Torpedo Destroyer",
    img: "/ships/quaoar_b.png",
    type: "Destroyer",
    variant: "B",
    variant_name: "Torpedo Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 30540,
    antiship: 5309,
    antiair: 1362,
    siege: 381,
    cruise_speed: 850,
    warp_speed: 4250,
    maxCount: 10,
    storage: 8500,
}, {
    name: "Taurus",
    title: "Pulse Cannon Destroyer",
    img: "/ships/taurus_a.png",
    type: "Destroyer",
    variant: "A",
    variant_name: "Offensive Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 36040,
    antiship: 6210,
    antiair: 1615,
    siege: 801,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 10,
    storage: 7000,
}, {
    name: "Taurus",
    title: "Assault Destroyer",
    img: "/ships/taurus_b.png",
    type: "Destroyer",
    variant: "B",
    variant_name: "Assault Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 48036,
    antiship: 6555,
    antiair: 501,
    siege: 1552,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 10,
    storage: 7500,
}, {
    name: "Taurus",
    title: "Defensive Destroyer",
    img: "/ships/taurus_c.png",
    type: "Destroyer",
    variant: "C",
    variant_name: "Defensive Type",
    command_points: 8,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 48036,
    antiship: 4830,
    antiair: 2059,
    siege: 338,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 10,
    storage: 7000,
}, {
    name: "Tundra",
    title: "Tactical Destroyer",
    img: "/ships/tundra_a.png",
    type: "Destroyer",
    variant: "A",
    variant_name: "Support Type",
    command_points: 9,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire", "Strategic Strike I"],
    hitpoints: 41190,
    antiship: 1350,
    antiair: 5127,
    siege: 5127,
    cruise_speed: 700,
    warp_speed: 3500,
    maxCount: 10,
    storage: 10000,
}, {
    name: "Tundra",
    title: "Aircraft Destroyer",
    img: "/ships/tundra_b.png",
    type: "Destroyer",
    variant: "B",
    variant_name: "Aircraft Type",
    command_points: 9,
    aircraft_space: null,
    aircraft_capacity: 2,
    aircraft_type: ["Small Fighter", "Medium Fighter"],
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 40030,
    antiship: 2022,
    antiair: 519,
    siege: 322,
    cruise_speed: 700,
    warp_speed: 3500,
    maxCount: 10,
    storage: 10000,
}, {
    name: "Winged Hussar",
    title: "Light Missile Destroyer",
    img: "/ships/wingedHussar_a.png",
    type: "Destroyer",
    variant: "A",
    variant_name: "Anti-Ship Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 22710,
    antiship: 4472,
    antiair: 336,
    siege: 1367,
    cruise_speed: 700,
    warp_speed: 3500,
    maxCount: 10,
    storage: 8500,
}, {
    name: "Winged Hussar",
    title: "Integrated Missile Destroyer",
    img: "/ships/wingedHussar_b.png",
    type: "Destroyer",
    variant: "B",
    variant_name: "Integrated Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 22710,
    antiship: 4100,
    antiair: 540,
    siege: 366,
    cruise_speed: 850,
    warp_speed: 4250,
    maxCount: 10,
    storage: 8500,
}, {
    name: "Winged Hussar",
    title: "Area-Denial Anti-Aircraft Destroyer",
    img: "/ships/wingedHussar_c.png",
    type: "Destroyer",
    variant: "C",
    variant_name: "Anti-Aircraft Type",
    command_points: 6,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire", "Anti-Aircraft Network I", "Firing Calibration"],
    hitpoints: 22710,
    antiship: 3360,
    antiair: 1105,
    siege: 72,
    cruise_speed: 850,
    warp_speed: 4250,
    maxCount: 10,
    storage: 9000,
}, {
    name: "CAS066",
    title: "Generic Cruiser",
    img: "/ships/cas066_a.png",
    type: "Cruiser",
    variant: "A",
    variant_name: "Integrated Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 71600,
    antiship: 10726,
    antiair: 432,
    siege: 3299,
    cruise_speed: 500,
    warp_speed: 2500,
    maxCount: 12,
    storage: 26000,
}, {
    name: "CAS066",
    title: "Artillery Cruiser",
    img: "/ships/cas066_b.png",
    type: "Cruiser",
    variant: "B",
    variant_name: "Artillery Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 63340,
    antiship: 15103,
    antiair: 378,
    siege: 6423,
    cruise_speed: 500,
    warp_speed: 2500,
    maxCount: 12,
    storage: 25000,
}, {
    name: "CAS066",
    title: "Aircraft Cruiser",
    img: "/ships/cas066_c.png",
    type: "Cruiser",
    variant: "C",
    variant_name: "Aircraft Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: 2,
    aircraft_type: ["Corvette"],
    row: "Front Row",
    flagship: ["Focus Fire", "Strategic Strike II"],
    hitpoints: 66400,
    antiship: 6150,
    antiair: 432,
    siege: 1377,
    cruise_speed: 500,
    warp_speed: 2500,
    maxCount: 12,
    storage: 26000,
}, {
    name: "CAS066",
    title: "Auxiliary Cruiser",
    img: "/ships/cas066_d.png",
    type: "Cruiser",
    variant: "D",
    variant_name: "Support Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 84844,
    antiship: 3975,
    antiair: 432,
    siege: 724,
    cruise_speed: 500,
    warp_speed: 2500,
    maxCount: 12,
    storage: 26000,
}, {
    name: "Callisto",
    title: "Cluster Torpedo Raid Ship",
    img: "/ships/callisto_a.png",
    type: "Cruiser",
    variant: "A",
    variant_name: "Torpedo Type",
    command_points: 20,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 79630,
    antiship: 14350,
    antiair: 216,
    siege: 3983,
    cruise_speed: 400,
    warp_speed: 2000,
    maxCount: 8,
    storage: 21000,
}, {
    name: "Callisto",
    title: "Heavy Torpedo Raid Ship",
    img: "/ships/callisto_b.png",
    type: "Cruiser",
    variant: "B",
    variant_name: "Anti-Ship Type",
    command_points: 20,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 79630,
    antiship: 18095,
    antiair: 126,
    siege: 3728,
    cruise_speed: 400,
    warp_speed: 2000,
    maxCount: 8,
    storage: 21000,
}, {
    name: "Callisto",
    title: "Heavy UAV Cruiser",
    img: "/ships/callisto_c.png",
    type: "Cruiser",
    variant: "C",
    variant_name: "Support Type",
    command_points: 20,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire", "Patrolling Defense"],
    hitpoints: 79630,
    antiship: 10950,
    antiair: 4801,
    siege: 3003,
    cruise_speed: 400,
    warp_speed: 2000,
    maxCount: 8,
    storage: 25000,
}, {
    name: "Chimera",
    title: "Heavy Cruiser",
    img: "/ships/chimera_a.png",
    type: "Cruiser",
    variant: "A",
    variant_name: "Ballistic Type",
    command_points: 20,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 89390,
    antiship: 14567,
    antiair: 180,
    siege: 1893,
    cruise_speed: 450,
    warp_speed: 2250,
    maxCount: 8,
    storage: 20000,
}, {
    name: "Chimera",
    title: "Cannon Cruiser",
    img: "/ships/chimera_b.png",
    type: "Cruiser",
    variant: "B",
    variant_name: "Heavy Cannon Type",
    command_points: 20,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 89390,
    antiship: 17650,
    antiair: 180,
    siege: 3342,
    cruise_speed: 450,
    warp_speed: 2250,
    maxCount: 8,
    storage: 25000,
}, {
    name: "Chimera",
    title: "Defensive Cruiser",
    img: "/ships/chimera_c.png",
    type: "Cruiser",
    variant: "C",
    variant_name: "Defensive Type",
    command_points: 20,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire", "Desperate Measures I"],
    hitpoints: 97270,
    antiship: 10914,
    antiair: null,
    siege: 2415,
    cruise_speed: 450,
    warp_speed: 2250,
    maxCount: 8,
    storage: 25000,
}, {
    name: "Conamara Chaos",
    title: "Railgun Cruiser",
    img: "/ships/conamaraChaos_a.png",
    type: "Cruiser",
    variant: "A",
    variant_name: "Railgun Type",
    command_points: 20,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 71600,
    antiship: 12380,
    antiair: 529,
    siege: 1320,
    cruise_speed: 450,
    warp_speed: 2250,
    maxCount: 8,
    storage: 20000,
}, {
    name: "Conamara Chaos",
    title: "High-Speed Plasma Cruiser",
    img: "/ships/conamaraChaos_b.png",
    type: "Cruiser",
    variant: "B",
    variant_name: "Plasma Type",
    command_points: 20,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 71600,
    antiship: 15908,
    antiair: 529,
    siege: 2622,
    cruise_speed: 450,
    warp_speed: 2250,
    maxCount: 8,
    storage: 20000,
}, {
    name: "Io",
    title: "Assault Ion Cannon Cruiser",
    img: "/ships/io_a.png",
    type: "Cruiser",
    variant: "A",
    variant_name: "Ion Cannon Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 62120,
    antiship: 18985,
    antiair: 189,
    siege: 3753,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 8,
    storage: 20000,
}, {
    name: "Io",
    title: "High-Speed Ion Cannon Cruiser",
    img: "/ships/io_b.png",
    type: "Cruiser",
    variant: "B",
    variant_name: "Anti-Ship Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire", "Siege Tactic I"],
    hitpoints: 62120,
    antiship: 15100,
    antiair: 189,
    siege: 946,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 8,
    storage: 20000,
}, {
    name: "Io",
    title: "Siege Ion Cannon Cruiser",
    img: "/ships/io_c.png",
    type: "Cruiser",
    variant: "C",
    variant_name: "Siege Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Front Row",
    flagship: ["Focus Fire"],
    hitpoints: 62120,
    antiship: 15647,
    antiair: 92,
    siege: 11979,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 8,
    storage: 20000,
}, {
    name: "Jaeger",
    title: "Heavy Aircraft Cruiser",
    img: "/ships/jaeger_a.png",
    type: "Cruiser",
    variant: "A",
    variant_name: "Support Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: 4,
    aircraft_type: ["Corvette"],
    row: "Back Row",
    flagship: ["Focus Fire", "Strategic Strike II"],
    hitpoints: 76190,
    antiship: 3000,
    antiair: 535,
    siege: 273,
    cruise_speed: 500,
    warp_speed: 2500,
    maxCount: 8,
    storage: 26000,
}, {
    name: "Jaeger",
    title: "Heavy Cannon Cruiser",
    img: "/ships/jaeger_b.png",
    type: "Cruiser",
    variant: "B",
    variant_name: "Anti-Ship Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire", "Combat Insertion"],
    hitpoints: 76190,
    antiship: 7971,
    antiair: 535,
    siege: 1147,
    cruise_speed: 500,
    warp_speed: 2500,
    maxCount: 8,
    storage: 27000,
}, {
    name: "KCCPV2.0",
    title: "Light Attack Cruiser",
    img: "/ships/kccpv_a.png",
    type: "Cruiser",
    variant: "A",
    variant_name: "Integrated Type",
    command_points: 16,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Back Row",
    flagship: ["Focus Fire", "Target Guidance I"],
    hitpoints: 52040,
    antiship: 8702,
    antiair: 1110,
    siege: 1965,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 12,
    storage: 25000,
}, {
    name: "KCCPV2.0",
    title: "Light Pulse Attack Cruiser",
    img: "/ships/kccpv_b.png",
    type: "Cruiser",
    variant: "B",
    variant_name: "Pulse Cannon Type",
    command_points: 16,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 52040,
    antiship: 9064,
    antiair: 1020,
    siege: 734,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 12,
    storage: 22000,
}, {
    name: "KCCPV2.0",
    title: "Light Railgun Cruiser",
    img: "/ships/kccpv_c.png",
    type: "Cruiser",
    variant: "C",
    variant_name: "Railgun Type",
    command_points: 16,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 52040,
    antiship: 9604,
    antiair: 1020,
    siege: 3632,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 12,
    storage: 25000,
}, {
    name: "KCCPV2.0",
    title: "Light Aircraft Cruiser",
    img: "/ships/kccpv_d.png",
    type: "Cruiser",
    variant: "D",
    variant_name: "Aircraft Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: 2,
    aircraft_type: ["Small Fighter", "Medium Fighter", "Large Fighter"],
    row: "Back Row",
    flagship: ["Focus Fire"],
    hitpoints: 52040,
    antiship: 5014,
    antiair: 930,
    siege: 464,
    cruise_speed: 650,
    warp_speed: 3250,
    maxCount: 12,
    storage: 22000,
}, {
    name: "Light Cone",
    title: "Multi-Role Missile Cruiser Cruiser",
    img: "/ships/lightCone_a.png",
    type: "Cruiser",
    variant: "A",
    variant_name: "Generic Type",
    command_points: 20,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire", "Anti-Aircraft Network II"],
    hitpoints: 69570,
    antiship: 12471,
    antiair: 6359,
    siege: 1072,
    cruise_speed: 450,
    warp_speed: 2250,
    maxCount: 8,
    storage: 26000,
}, {
    name: "Light Cone",
    title: "Area-Denial Anti-Aircraft Cruiser",
    img: "/ships/lightCone_b.png",
    type: "Cruiser",
    variant: "B",
    variant_name: "Anti-Aircraft Type",
    command_points: 20,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 69570,
    antiship: 5850,
    antiair: 6930,
    siege: 570,
    cruise_speed: 450,
    warp_speed: 2250,
    maxCount: 8,
    storage: 26000,
}, {
    name: "Light Cone",
    title: "Offensive Missile Cruiser",
    img: "/ships/lightCone_c.png",
    type: "Cruiser",
    variant: "C",
    variant_name: "Assault Type",
    command_points: 20,
    aircraft_space: null,
    aircraft_capacity: null,
    row: "Middle Row",
    flagship: ["Focus Fire"],
    hitpoints: 69570,
    antiship: 13500,
    antiair: 236,
    siege: 1372,
    cruise_speed: 450,
    warp_speed: 2250,
    maxCount: 8,
    storage: 25000,
}, {
    name: "Predator",
    title: "Aircraft Cruiser",
    img: "/ships/predator_a.png",
    type: "Cruiser",
    variant: "A",
    variant_name: "Generic Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: 4,
    aircraft_type: ["Small Fighter", "Medium Fighter"],
    row: "Back Row",
    flagship: ["Focus Fire", "Strategic Strike II"],
    hitpoints: 76190,
    antiship: 3114,
    antiair: 572,
    siege: 119,
    cruise_speed: 500,
    warp_speed: 2500,
    maxCount: 8,
    storage: 26000,
}, {
    name: "Predator",
    title: "Tactical Aircraft Cruiser",
    img: "/ships/predator_b.png",
    type: "Cruiser",
    variant: "B",
    variant_name: "Tactical Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: 4,
    aircraft_type: ["Small Fighter", "Medium Fighter"],
    row: "Back Row",
    flagship: ["Focus Fire", "Strategic Strike II"],
    hitpoints: 76190,
    antiship: 600,
    antiair: 216,
    siege: 60,
    cruise_speed: 500,
    warp_speed: 2500,
    maxCount: 8,
    storage: 25000,
}, {
    name: "Predator",
    title: "Anti-Aircraft Cruiser",
    img: "/ships/predator_c.png",
    type: "Cruiser",
    variant: "C",
    variant_name: "Anti-Aircraft Type",
    command_points: 18,
    aircraft_space: null,
    aircraft_capacity: 4,
    aircraft_type: ["Small Fighter", "Medium Fighter"],
    row: "Back Row",
    flagship: ["Focus Fire", "Anti-Aircraft Network I"],
    hitpoints: 76190,
    antiship: 600,
    antiair: 1988,
    siege: 60,
    cruise_speed: 500,
    warp_speed: 2500,
    maxCount: 8,
    storage: 27000,
}, {
    name: "Constantine the Great",
    title: "Multi-Role Battlecruiser",
    img: "/ships/constantineTheGreat.png",
    type: "Battlecruiser",
    variant: "A",
    variant_name: "Super Type",
    command_points: 35,
    row: "Middle Row",
    flagship: ["Focus Fire", "Siege Tactic II"],
    hitpoints: 141550,
    cruise_speed: 400,
    warp_speed: 2000,
    maxCount: 6,
    storage: 125000,
    modules: [{
        name: "M1",
        antiship: 11917,
        antiair: 0,
        siege: 2502
    }, {
        name: "M2",
        antiship: 19885,
        antiair: 0,
        siege: 2784
    }, {
        name: "A1",
        antiship: 24917,
        antiair: 0,
        siege: 2016
    }, {
        name: "A2",
        antiship: 40666,
        antiair: 1643,
        siege: 3138
    }, {
        name: "B1",
        antiship: 10628,
        antiair: 270,
        siege: 1461
    }, {
        name: "B2",
        antiship: 5175,
        antiair: 2040,
        siege: 0
    }, {
        name: "B3",
        antiship: 2400,
        antiair: 1548,
        siege: 0
    }, {
        name: "C1"
    }, {
        name: "C2",
        aircraft_capacity: 1,
        aircraft_type: ["Small Fighter", "Medium Fighter"]
    }, {
        name: "C3"
    }, {
        name: "D1",
        antiship: 0,
        antiair: 1011,
        siege: 0
    }, {
        name: "D2"
    }, {
        name: "D3"
    }]
}, {
    name: "Eternal Storm",
    title: "Attack Battlecruiser",
    img: "/ships/eternalStorm.png",
    type: "Battlecruiser",
    variant: "A",
    variant_name: "Super Type",
    command_points: 32,
    row: "Middle Row",
    flagship: ["Focus Fire", "Patrolling Defense"],
    hitpoints: 146740,
    cruise_speed: 450,
    warp_speed: 2250,
    maxCount: 6,
    storage: 120000,
    modules: [{
        name: "M1",
        antiship: 16000,
        antiair: 0,
        siege: 3360
    }, {
        name: "M2",
        antiship: 15692,
        antiair: 1883,
        siege: 2824
    }, {
        name: "A1",
        antiship: 12240,
        antiair: 396,
        siege: 1539
    }, {
        name: "A2",
        antiship: 11900,
        antiair: 0,
        siege: 10440
    }, {
        name: "A3",
        antiship: 11345,
        antiair: 593,
        siege: 1440
    }, {
        name: "B1",
        antiship: 5850,
        antiair: 126,
        siege: 1113
    }, {
        name: "B2",
        antiship: 900,
        antiair: 405,
        siege: 60
    }, {
        name: "C1",
        antiship: 0,
        antiair: 3888,
        siege: 0
    }, {
        name: "C2"
    }, {
        name: "C3"
    }, {
        name: "D1",
        antiship: 6857,
        antiair: 0,
        siege: 1028
    }, {
        name: "D2",
        antiship: 0,
        antiair: 432,
        siege: 0
    }]
}, {
    name: "Spear of Uranus",
    title: "Heavy Battlecruiser",
    img: "/ships/spearOfUranus.png",
    type: "Battlecruiser",
    variant: "A",
    variant_name: "Super Type",
    command_points: 35,
    row: "Front Row",
    flagship: ["Focus Fire", "Combat Surge"],
    hitpoints: 180470,
    cruise_speed: 250,
    warp_speed: 1250,
    maxCount: 6,
    storage: 115000,
    modules: [{
        name: "M1",
        antiship: 12950,
        antiair: 0,
        siege: 11310
    }, {
        name: "M2",
        antiship: 12857,
        antiair: 0,
        siege: 1800
    }, {
        name: "A1",
        antiship: 13120,
        antiair: 636,
        siege: 3075
    }, {
        name: "A2",
        antiship: 15986,
        antiair: 216,
        siege: 2880
    }, {
        name: "A3",
        antiship: 17220,
        antiair: 1026,
        siege: 1800
    }, {
        name: "B1",
        antiship: 5940,
        antiair: 680,
        siege: 259
    }, {
        name: "B2",
        aircraft_capacity: 3,
        aircraft_type: ["Corvette"]
    }, {
        name: "B3"
    }, {
        name: "C1"
    }, {
        name: "C2"
    }, {
        name: "C3",
        antiship: 0,
        antiair: 410,
        siege: 0
    }]
}, {
    name: "ST59",
    title: "Defensive Battlecruiser",
    img: "/ships/st59.png",
    type: "Battlecruiser",
    variant: "A",
    variant_name: "Super Type",
    command_points: 28,
    row: "Middle Row",
    flagship: ["Focus Fire", "Desperate Measures II"],
    hitpoints: 136510,
    cruise_speed: 450,
    warp_speed: 2250,
    maxCount: 6,
    storage: 130000,
    modules: [{
        name: "M1",
        antiship: 10875,
        antiair: 0,
        siege: 3528
    }, {
        name: "M2",
        antiship: 11400,
        antiair: 0,
        siege: 960
    }, {
        name: "M3",
        antiship: 11200,
        antiair: 0,
        siege: 2266
    }, {
        name: "A1",
        antiship: 7875,
        antiair: 216,
        siege: 1206
    }, {
        name: "A2",
        antiship: 9900,
        antiair: 0,
        siege: 1923
    }, {
        name: "A3",
        antiship: 7500,
        antiair: 787,
        siege: 1200
    }, {
        name: "B1",
        antiship: 8188,
        antiair: 0,
        siege: 1185
    }, {
        name: "B2",
        aircraft_capacity: 2
    }, {
        name: "B3"
    }, {
        name: "C1"
    }, {
        name: "C2"
    }, {
        name: "C3"
    }]
}, {
    name: "Thunderbolt Star",
    title: "Multi-Role Arsenal Ship",
    img: "/ships/thunderboltStar.png",
    type: "Battlecruiser",
    variant: "A",
    variant_name: "Super Type",
    command_points: 35,
    row: "Middle Row",
    flagship: ["Focus Fire", "Multi-Target Counterattack"],
    hitpoints: 146740,
    cruise_speed: 400,
    warp_speed: 2000,
    maxCount: 3,
    storage: 120000,
    modules: [{
        name: "M1",
        antiship: 40628,
        antiair: 0,
        siege: 8562
    }, {
        name: "M2",
        antiship: 27168,
        antiair: 0,
        siege: 5705
    }, {
        name: "M3",
        antiship: 33120,
        antiair: 0,
        siege: 3312
    }, {
        name: "A1",
        antiship: 12636,
        antiair: 1266,
        siege: 1407
    }, {
        name: "A2",
        antiship: 14184,
        antiair: 0,
        siege: 1490
    }, {
        name: "B1",
        antiship: 3375,
        antiair: 465,
        siege: 0
    }, {
        name: "B2",
        antiship: 0,
        antiair: 345,
        siege: 0
    }, {
        name: "C1"
    }, {
        name: "C2"
    }, {
        name: "D1",
        antiship: 9140,
        antiair: 1164,
        siege: 970
    }, {
        name: "D2",
        antiship: 9948,
        antiair: 0,
        siege: 2112
    }, {
        name: "E1",
        antiship: 6990,
        antiair: 910,
        siege: 759
    }, {
        name: "E2",
        antiship: 0,
        antiair: 633,
        siege: 0
    }]
}, {
    name: "Ediacaran",
    title: "Heavy Firepower Auxiliary Ship",
    img: "/ships/ediacaran.png",
    type: "Auxiliary Ship",
    variant: "A",
    variant_name: "Super Type",
    command_points: 40,
    row: "Middle Row",
    flagship: ["Focus Fire", "Fleet Dock II"],
    hitpoints: 240460,
    cruise_speed: 420,
    warp_speed: 2100,
    maxCount: 2,
    storage: 105000,
    modules: [{
        name: "M1",
        antiship: 11057,
        antiair: 394,
        siege: 1756
    }, {
        name: "M2",
        antiship: 12000,
        antiair: 319,
        siege: 3150
    }, {
        name: "A1"
    }, {
        name: "A2"
    }, {
        name: "A3"
    }, {
        name: "B1",
        antiship: 0,
        antiair: 4608,
        siege: 0
    }, {
        name: "B2"
    }, {
        name: "B3"
    }, {
        name: "C1"
    }, {
        name: "C2",
        aircraft_capacity: 3,
        aircraft_type: ["Corvette"]
    }, {
        name: "D1"
    }, {
        name: "D2"
    }]
}, {
    name: "FSV830",
    title: "Fast Tactical Auxiliary Ship",
    img: "/ships/fsv830.png",
    type: "Auxiliary Ship",
    variant: "A",
    variant_name: "Super Type",
    command_points: 40,
    row: "Back Row",
    flagship: ["Focus Fire", "Sailing Speed Coordination I", "Fleet Dock I"],
    hitpoints: 180470,
    cruise_speed: 560,
    warp_speed: 2800,
    maxCount: 2,
    storage: 125000,
    modules: [{
        name: "A1"
    }, {
        name: "A2"
    }, {
        name: "A3"
    }, {
        name: "B1"
    }, {
        name: "B2"
    }, {
        name: "B3"
    }, {
        name: "C1"
    }, {
        name: "C2"
    }, {
        name: "D1",
        aircraft_capacity: 2,
        aircraft_type: ["Small Fighter", "Medium Fighter"]
    }, {
        name: "D2"
    }, {
        name: "E1",
        antiship: 0,
        antiair: 882,
        siege: 0
    }, {
        name: "E2",
        aircraft_capacity: 3,
        aircraft_type: ["Corvette"]
    }]
}, {
    name: "CV3000",
    title: "High-Speed Carrier",
    img: "/ships/cv3000.png",
    type: "Carrier",
    variant: "A",
    variant_name: "Super Type",
    command_points: 40,
    row: "Back Row",
    flagship: ["Focus Fire", "Strategic Strike II", "Strategic Strike III"],
    hitpoints: 278340,
    cruise_speed: 400,
    warp_speed: 2000,
    maxCount: 5,
    storage: 150000,
    modules: [{
        name: "M1",
        aircraft_capacity: 8,
        aircraft_type: ["Small Fighter", "Medium Fighter", "Large Fighter", "Corvette"]
    }, {
        name: "M2",
        aircraft_capacity: 5,
        aircraft_type: ["Small Fighter", "Medium Fighter", "Large Fighter"]
    }, {
        name: "M3",
        aircraft_capacity: 8,
        aircraft_type: ["Small Fighter", "Medium Fighter", "Large Fighter"]
    }, {
        name: "A1",
        antiship: 6500,
        antiair: 297,
        siege: 619
    }, {
        name: "A2",
        antiship: 2700,
        antiair: 354,
        siege: null
    }, {
        name: "B1",
        antiship: 1200,
        antiair: 210,
        siege: 70
    }, {
        name: "B2",
        aircraft_capacity: 3,
        aircraft_type: ["Corvette"]
    }, {
        name: "B3"
    }]
}, {
    name: "Eternal Heavens",
    title: "UAV Carrier",
    img: "/ships/eternalHeavens.png",
    type: "Carrier",
    variant: "A",
    variant_name: "Super Type",
    command_points: 40,
    row: "Back Row",
    flagship: ["Focus Fire", "Strategic Strike II", "Strategic Strike III"],
    hitpoints: 298690,
    cruise_speed: 350,
    warp_speed: 2750,
    maxCount: 5,
    storage: 150000,
    modules: [{
        name: "M1",
        aircraft_capacity: 3,
        aircraft_type: ["Small Fighter", "Medium Fighter"]
    }, {
        name: "M2"
    }, {
        name: "M3"
    }, {
        name: "A1",
        antiship: 10250,
        antiair: 472,
        siege: 3815
    }, {
        name: "A2",
        antiship: 8857,
        antiair: 252,
        siege: 828
    }, {
        name: "A3"
    }, {
        name: "B1"
    }, {
        name: "B2"
    }, {
        name: "B3"
    }, {
        name: "C1"
    }, {
        name: "C2"
    }, {
        name: "C3"
    }]
}, {
    name: "Marshal Crux",
    title: "Carrier",
    img: "/ships/marshalCrux.png",
    type: "Carrier",
    variant: "A",
    variant_name: "Super Type",
    command_points: 40,
    row: "Back Row",
    flagship: ["Focus Fire", "Strategic Strike II", "Strategic Strike III"],
    hitpoints: 278340,
    cruise_speed: 400,
    warp_speed: 2000,
    maxCount: 5,
    storage: 150000,
    modules: [{
        name: "M1",
        antiship: 16080,
        antiair: 691,
        siege: 1908
    }, {
        name: "M2",
        antiship: 13628,
        antiair: 162,
        siege: 2275
    }, {
        name: "A1",
        aircraft_capacity: 6,
        aircraft_type: ["Small Fighter", "Medium Fighter", "Large Fighter"]
    }, {
        name: "A2",
        aircraft_capacity: 6,
        aircraft_type: ["Corvette"]
    }, {
        name: "B1"
    }, {
        name: "B2"
    }, {
        name: "C1",
        aircraft_capacity: 4,
        aircraft_type: ["Small Fighter", "Medium Fighter"]
    }, {
        name: "C2",
        antiship: 5200,
        antiair: 504,
        siege: 392
    }, {
        name: "C3"
    }]
}, {
    name: "Solar Whale",
    title: "Armed Tactical Carrier",
    img: "/ships/solarWhale.png",
    type: "Carrier",
    variant: "A",
    variant_name: "Super Type",
    command_points: 45,
    row: "Middle Row",
    flagship: ["Focus Fire", "Strategic Strike II", "Strategic Strike III"],
    hitpoints: 329430,
    cruise_speed: 250,
    warp_speed: 1250,
    maxCount: 5,
    storage: 130000,
    modules: [{
        name: "M1",
        aircraft_capacity: 6,
        aircraft_type: ["Corvette"]
    }, {
        name: "M2",
        aircraft_capacity: 8,
        aircraft_type: ["Small Fighter", "Medium Fighter", "Large Fighter"]
    }, {
        name: "A1",
        antiship: 9648,
        antiair: 589,
        siege: 959
    }, {
        name: "A2",
        antiship: 8749,
        antiair: 589,
        siege: 648
    }, {
        name: "A3",
        antiship: 8888,
        antiair: 1021,
        siege: 630
    }, {
        name: "B1"
    }, {
        name: "B2",
        aircraft_capacity: 3,
        aircraft_type: ["Corvette"]
    }, {
        name: "C1",
        aircraft_capacity: 5,
        aircraft_type: ["Small Fighter", "Medium Fighter", "Large Fighter"]
    }, {
        name: "C2",
        antiship: 0,
        antiair: 0,
        siege: 6652
    }, {
        name: "C3",   
        antiship: 2618,
        antiair: 1178,
        siege: 0
    }]
}
];

export { data };
